### PR TITLE
fix: release VF assigned to the Pod back to the host network namespace

### LINKED ISSUE #3437: When the pod using the sriov interface is deleted, although the sriov interface has been returned to host network namespace, but the sriov interface has not been restored to its original name.
# Bug Report
when delete a pod using the sriov interface

## Expected Behavior
the sriov interface has been returned to host network namespace, 
and the sriov interface has been restored to its original name

## Actual Behavior
the sriov interface has been returned to host network namespace, and the sriov interface has not been restored to its original name

## Steps to Reproduce the Problem

1.kubectl create a pod using the sriov interface
2.kubectl delete the pod in step 1
3.On the node where the pod is located, use ip a to check the network port name and find that the network port name is the pod‘s interface name before like eth0, not the original network port name in the host network namespace of this node.

### PR DESCRIPTION
**Pull request by guof888**
# Pull Request

- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR

fix: release VF assigned to the Pod back to the host network namespace when delete pod

## Which issue(s) this PR fixes

Fixes #3437 

## WHAT
Add a symmetric operation to configure the siriov interface (setupSriovInterface) for the pod: release the sriovs interface

## HOW
1.move VF to the host network namespace
2.renames the VF device from `eth0` to its original name

### CODE REVIEW

File: pkg/daemon/ovs_linux.go [hunk 1]
```diff
@@ -57,7 +57,7 @@ func (csh cniServerHandler) configureDpdkNic(podName, podNamespace, provider, ne
 	return ovs.SetInterfaceBandwidth(podName, podNamespace, ifaceID, egress, ingress)
 }
 
-func (csh cniServerHandler) configureNic(podName, podNamespace, provider, netns, containerID, vfDriver, ifName, mac string, mtu int, ip, gateway string, isDefaultRoute, detectIPConflict bool, routes []request.Route, _, _ []string, ingress, egress, deviceID, nicType, latency, limit, loss, jitter string, gwCheckMode int, u2oInterconnectionIP string) error {
+func (csh cniServerHandler) configureNic(podName, podNamespace, provider, netns, containerID, vfDriver, ifName, mac string, mtu int, ip, gateway string, isDefaultRoute, detectIPConflict bool, routes []request.Route, _, _ []string, ingress, egress, deviceID, nicType, latency, limit, loss, jitter string, gwCheckMode int, u2oInterconnectionIP, oldPodName string) error {
```
Comment (zhangzujian) [inline pkg/daemon/ovs_linux.go:60]: `pkg/daemon/ovs_windows.go` should be also updated.

File: pkg/daemon/ovs_linux.go [hunk 2]
```diff
@@ -126,7 +154,65 @@ func (csh cniServerHandler) configureNic(podName, podNamespace, provider, netns,
...
+		return nil
+	})
+	if err != nil {
+		klog.Errorf(err.Error())
+	}
+
+	return nil
+}
+
+func (csh cniServerHandler) deleteNic(podName, podNamespace, containerID, netns, deviceID, ifName, nicType, provider string) error {
```
Comment (zhangzujian) [inline pkg/daemon/ovs_linux.go:210]: `pkg/daemon/ovs_windows.go` should be also updated.

**Comment by zhangzujian** [comment]
```txt
pkg\daemon\ovs_windows.go:26: not enough arguments in call to csh.configureNic
	have (string, string, string, string, string, string, string, string, int, string, string, bool, bool, []request.Route, []string, []string, string, string, string, string, string, string, string, string, int, string)
	want (string, string, string, string, string, string, string, string, int, string, string, bool, bool, []request.Route, []string, []string, string, string, string, string, string, string, string, string, int, string, string)
```

File: pkg/util/const.go [hunk 3]
```diff
@@ -76,6 +76,8 @@ const (
 	SecurityGroupAnnotationTemplate = "%s.kubernetes.io/security_groups"
 	LiveMigrationAnnotationTemplate = "%s.kubernetes.io/allow_live_migration"
 	DefaultRouteAnnotationTemplate  = "%s.kubernetes.io/default_route"
+	VfRepresentorName               = "%s.kubernetes.io/vf_representor"
+	VfName                          = "%s.kubernetes.io/vf"
```
Comment (zhangzujian) [inline pkg/util/const.go:80]:
```suggestion
	VfRepresentorNameTemplate       = "%s.kubernetes.io/vf_representor"
	VfNameTemplate                  = "%s.kubernetes.io/vf"
```

**Review by zhangzujian — APPROVED** [review]
