### PR TITLE
fix: cancel delete staticroute when it's used by NatRule

### LINKED ISSUE #1732: gc will influence pod use eip or snat.
# Expected Behavior
gc won't influence services in use.

# Actual Behavior
gc will delete pod's staticroute created by eip or snat.

# Steps to Reproduce the Problem

1. create a pod with eip or snat
2. kube-ovn-controller switch active and standby

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```v1.23.6```

- kube-ovn version:
  
  ```master```

# gc code
https://github.com/kubeovn/kube-ovn/blob/d1b291ed659b079b0b7fd5e39f8cb7b60f4a43db/pkg/controller/gc.go#L640-L656

L648 deletestaticroute in use will cause this issue.

### PR DESCRIPTION
**Pull request by xujunjie-cover**
gc will delete staticroute whice used by natrule.

Signed-off-by: xujunjie-cover <xujunjielxx@163.com>

- [x] Make sure you have followed [Kube-OVN Code Style](../CODE_STYLE.md).

#### What type of this PR
Examples of user facing changes:
- Bug fixes

#### Which issue(s) this PR fixes:
Fixes #1732

### CODE REVIEW

**Review by oilbeater — APPROVED** [review]

File: pkg/controller/gc.go [hunk 1]
```diff
@@ -647,6 +647,10 @@ func (c *Controller) gcStaticRoute() error {
 	for _, route := range routes {
 		if route.CIDR != "0.0.0.0/0" && route.CIDR != "::/0" && c.ipam.ContainAddress(route.CIDR) {
 			klog.Infof("gc static route %s %s %s", route.Policy, route.CIDR, route.NextHop)
+			exist, err := c.ovnLegacyClient.NatRuleExists(route.CIDR)
```
Comment (oilbeater) [inline pkg/controller/gc.go:650]: Just find some problem after merge. The logical should come before the `klog.Infof("gc static route %s %s %s", route.Policy, route.CIDR, route.NextHop)` and the err should be logged

**Review by oilbeater — CHANGES_REQUESTED** [review]

File: pkg/controller/gc.go (hunk 1 above)
Comment (xujunjie-cover) [reply pkg/controller/gc.go:650]: Sorry, It's my carelessness. I will create a new pr to repair it.
