### PR TITLE
fix security groups changed when vm is shut down

### LINKED ISSUE #4975: [BUG] modifying the security group while the computer is shut down will result in the security group remaining
### Kube-OVN Version

v1.14.0

### Kubernetes Version

v1.29.5

### Operation-system/Kernel Version

"Ubuntu 22.04.5 LTS" 6.8.0-52-generic

### Description

VM在关机状态下删减安全组会导致下一次重启虚机的时候，删减的安全组残留
e.g.
1、VM开机状态下绑定安全组sg1和sg2（通过在VM上添加安全组的注解），此时关机后virt-launcher的pod被删除，但是由于是vm，且lsp是保留的，当前的代码逻辑中不会清理该lsp关联的安全组规则
2、此时修改VM上的安全组注解，将sg2删除再开机，此时发现虽然在lsp的external_id里已经解绑了sg2，但是sg2对应的pg和address set都没有更新，导致ovn的流表中仍存在vm绑定sg2的规则

### Steps To Reproduce

1、VM绑定安全组sg
2、关机后删除VM上的安全组sg
3、重启VM，发现sg的规则仍然残留

### Current Behavior

关机后删减VM上的安全组会导致VM重启后安全组残留

### Expected Behavior

关机状态下删减VM的安全组后，在VM重启后会同步删除对应的安全组规则

### PR DESCRIPTION
**Pull request by zhaocongqi**
# Pull Request

- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR

Examples of user facing changes:

- Bug fixes

## Which issue(s) this PR fixes

Fixes #4975

### CODE REVIEW

File: pkg/util/slice.go [hunk 1]
```diff
@@ -27,6 +27,31 @@ func DiffStringSlice(slice1, slice2 []string) []string {
...
+	for _, s2 := range slice2 {
+		uniqueMap[s2] = struct{}{}
+	}
+
+	for key := range uniqueMap {
+		union = append(union, key)
+	}
+
+	return union
+}
```
Comment (zhangzujian) [inline pkg/util/slice.go:53]:
```suggestion
func UnionStringSlice(slices ...[]string) []string {
	union := set.New[string]()
	for _, s := range slices {
		union.Insert(s...)
	}
	return union.UnsortedList()
}
```

**Review by zbb88888 — APPROVED** [review]

File: pkg/controller/pod.go [hunk 2]
```diff
@@ -588,8 +599,10 @@ func (c *Controller) reconcileAllocateSubnets(pod *v1.Pod, needAllocatePodNets [
 				}
 			}
 
-			if securityGroupAnnotation != "" {
-				sgNames := strings.Split(securityGroups, ",")
+			if securityGroupAnnotation != "" || oldSgList != nil {
+				securityGroups := strings.ReplaceAll(securityGroupAnnotation, " ", "")
+				newSgList := strings.Split(securityGroups, ",")
+				sgNames := util.UnionStringSlice(oldSgList, newSgList)
```
Comment (zhangzujian) [inline pkg/controller/pod.go:605]: What happens if all security groups are deleted before starting the stopped VM?

File: pkg/controller/pod.go [hunk 3]
```diff
@@ -571,8 +571,19 @@ func (c *Controller) reconcileAllocateSubnets(pod *v1.Pod, needAllocatePodNets [
 				DHCPv6OptionsUUID: subnet.Status.DHCPv6OptionsUUID,
 			}
 
+			var oldSgList []string
+			if vmKey != "" {
```
Comment (zhangzujian) [inline pkg/controller/pod.go:575]: Does this bug affects StatefulSets?

File: pkg/controller/pod.go (hunk 2 above)
Comment (zbb88888) [reply pkg/controller/pod.go:605]: sg not exist, sg update logic will not enque

Comment (zhangzujian) [reply pkg/controller/pod.go:605]: My fault. OR logic is used so security groups will be updated as expected.

File: pkg/controller/pod.go (hunk 3 above)
Comment (zhaocongqi) [reply pkg/controller/pod.go:575]: yes,in some cases stateful set will have the same problem,i will fix it later

**Review by zhangzujian — APPROVED** [review]
