### PR TITLE
fix: Do not Recreate Logical_Router_Port when Vpc recreated

### LINKED ISSUE #1569: Do not Recreate Logical_Router_Port when Vpc recreated
# Expected Behavior

```shell
$ kubectl-ko nbctl show alpine-vpc
router abae48a2-6e93-4338-a586-0a720e29eea6 (alpine-vpc)
    port alpine-vpc-alpine-subnet-2
        mac: "00:00:00:92:35:DB"
        networks: ["172.24.0.1/16"]
    port alpine-vpc-alpine-subnet-1
        mac: "00:00:00:47:C9:3D"
        networks: ["172.23.0.1/16"]
```

# Actual Behavior

```shell
$ kubectl-ko nbctl show alpine-vpc
router abae48a2-6e93-4338-a586-0a720e29eea6 (alpine-vpc)
```

# Steps to Reproduce the Problem

1. `kubectl create -f vpc-subnet.yaml`
2. `kubectl delete vpc alpine-vpc`
3. `kubectl apply -f vpc-subnet.yaml`

`vpc-subnet.yaml`

```yaml
apiVersion: kubeovn.io/v1
kind: Vpc
metadata:
  name: alpine-vpc
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: alpine-subnet-1
spec:
  cidrBlock: 172.23.0.0/16
  default: false
  disableGatewayCheck: false
  disableInterConnection: false
  gateway: 172.23.0.1
  gatewayNode: ""
  gatewayType: distributed
  logicalGateway: false
  natOutgoing: false
  private: false
  protocol: IPv4
  provider: ovn
  vpc: alpine-vpc
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: alpine-subnet-2
spec:
  cidrBlock: 172.24.0.0/16
  default: false
  disableGatewayCheck: false
  disableInterConnection: false
  gateway: 172.24.0.1
  gatewayNode: ""
  gatewayType: distributed
  logicalGateway: false
  natOutgoing: false
  private: false
  protocol: IPv4
  provider: ovn
  vpc: alpine-vpc
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

  ```

- kube-ovn version:
  
  ```
  v1.10.0
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  "CentOS Stream 8"
  5.4.181-1.el8.elrepo.x86_64
  ```

### PR DESCRIPTION
**Pull request by lrh3321**
#### What type of this PR
Examples of user facing changes:

- Bug fixes

1. Recreate Logical_Router_Port when Vpc recreated
2. New method to check if Logical_Router, Logical_Router_Port exists
3. New method to Create Logical_Router_Port by libovsdb

#### Which issue(s) this PR fixes:
Fixes #1569

### CODE REVIEW

File: pkg/ovs/util.go [hunk 1]
```diff
@@ -23,3 +23,11 @@ func trimCommandOutput(raw []byte) string {
 	output := strings.TrimSpace(string(raw))
 	return strings.Trim(output, "\"")
 }
+
+func LogicalRouterPortName(lr, ls string) string {
+	return fmt.Sprintf("%s-%s", lr, ls)
+}
+
+func LogicalSwitchPortName(lr, ls string) string {
```
Comment (hongzhen-ma) [inline pkg/ovs/util.go:31]: Is this func used?

**Review by hongzhen-ma — CHANGES_REQUESTED** [review]

File: pkg/ovs/util.go (hunk 1 above)
Comment (lrh3321) [reply pkg/ovs/util.go:31]: I want to replace all the `fmt.Sprintf("%s-%s", ls, lr)`, `fmt.Sprintf("%s-%s", lr, ls)` to `LogicalSwitchPortName`, `LogicalRouterPortName`

https://github.com/kubeovn/kube-ovn/blob/337f6e05a6b12277eafd86689a7d6604a9cc44ae/pkg/ovs/ovn-nbctl-legacy.go#L414
https://github.com/kubeovn/kube-ovn/blob/337f6e05a6b12277eafd86689a7d6604a9cc44ae/pkg/ovs/ovn-nbctl-legacy.go#L761
https://github.com/kubeovn/kube-ovn/blob/337f6e05a6b12277eafd86689a7d6604a9cc44ae/pkg/ovs/ovn-nbctl-legacy.go#L762
https://github.com/kubeovn/kube-ovn/blob/337f6e05a6b12277eafd86689a7d6604a9cc44ae/pkg/ovs/ovn-nbctl-legacy.go#L774
https://github.com/kubeovn/kube-ovn/blob/337f6e05a6b12277eafd86689a7d6604a9cc44ae/pkg/ovs/ovn-nbctl-legacy.go#L775
https://github.com/kubeovn/kube-ovn/blob/337f6e05a6b12277eafd86689a7d6604a9cc44ae/pkg/ovs/ovn-nbctl-legacy.go#L2506

File: pkg/controller/vpc.go [hunk 2]
```diff
@@ -162,6 +162,43 @@ func (c *Controller) handleUpdateVpcStatus(key string) error {
...
+			subnet, err := c.subnetsLister.Get(subnetName)
+			if err != nil {
+				if k8serrors.IsNotFound(err) {
+					continue
+				}
+				klog.ErrorS(err, "unable to get subnet", "subnet", subnetName)
+				return err
+			}
+
+			klog.V(1).InfoS("router port not exists, trying to create", "vpc", vpc.Name, "subnet", subnetName)
```
[the remark this answers is not in the document]
Comment (lrh3321) [reply pkg/controller/vpc.go:190]: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md#what-method-to-use

`klog.V(1).InfoS` - A reasonable default log level if you don't want verbosity.

- Information about config (listening on X, watching Y)
- Errors that repeat frequently that relate to conditions that can be corrected (pod detected as unhealthy)

> As per the comments, the practical default level is V(2). Developers and QE environments may wish to run at V(3) or V(4). If you wish to change the log level, you can pass in -v=X where X is the desired maximum level to log.

File: pkg/ovs/util.go (hunk 1 above)
Comment (hongzhen-ma) [reply pkg/ovs/util.go:31]: OK. The function name may not be so sutiable.

File: pkg/ovs/ovn-nb-logical_router.go [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+			return nil, nil
+		}
+		return nil, fmt.Errorf("failed to get logical router %s: %v", name, err)
+	}
+
+	return result[0], nil
+}
+
+func (c OvnClient) LogicalRouterExists(name string) (bool, error) {
+	lsp, err := c.GetLogicalRouter(name, true)
```
[the remark this answers is not in the document]
Comment (lrh3321) [reply pkg/ovs/ovn-nb-logical_router.go]: I forgot to rename it.:sweat_smile:

**Review by hongzhen-ma — APPROVED** [review]
