### PR TITLE
fix encap_ip will be lost when we restart the ovs-dpdk node

### LINKED ISSUE #2542: if we restart the ovs-dpdk node, the ENCAP_IP will be lost
# Expected Behavior
the ENCAP_IP won't be lost

# Actual Behavior
the ENCAP_IP is  lost
# Steps to Reproduce the Problem

1.restart ovs-dpdk node
1.
1.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

### PR DESCRIPTION
**Pull request by lynn901**
- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

#### What type of this PR
Examples of user facing changes:
- Bug fixes

#### Which issue(s) this PR fixes:
Fixes #2542

### CODE REVIEW

File: dist/images/start-ovs-dpdk-v2.sh [hunk 1]
```diff
@@ -103,11 +103,12 @@ esac
 
 ovs-vsctl set port ${DPDK_TUNNEL_IFACE} tag=${VLAN_TAG}
 
-ip addr add ${ENCAP_IP} dev ${DPDK_TUNNEL_IFACE}
 fi
 
 ip link set ${DPDK_TUNNEL_IFACE} up
 
+ip addr add ${ENCAP_IP} dev ${DPDK_TUNNEL_IFACE}
```
Comment (oilbeater) [inline dist/images/start-ovs-dpdk-v2.sh:110]: `add` will report error if the address already exists when just restart the pod, we should use `replace` instead

**Review by oilbeater — CHANGES_REQUESTED** [review]

File: dist/images/start-ovs-dpdk-v2.sh (hunk 1 above)
Comment (lynn901) [reply dist/images/start-ovs-dpdk-v2.sh:110]: > 
ack， i will change it

**Review by oilbeater — APPROVED** [review]
