### PR TITLE
fix memory overflow, add mac_binding related options to router

### LINKED ISSUE #4604: [BUG] mac_binding cause memoryy overflow
### Kube-OVN Version

v1.13.0

### Kubernetes Version

1.31.0

### Operation-system/Kernel Version

3.10.0-1160.83.1.el7.x86_64

### Description

ovs-vswitchd have a high memory usage, and openflows count increase to 10w+
image

### Steps To Reproduce

1. create deploy A
2. create clusterIP service A related to deploy A
3. recreate deploy A' Pod  

### Current Behavior

one pod will left a gc Mac_binding table 

### Expected Behavior

one pod will not left a gc Mac_binding table

### PR DESCRIPTION
**Pull request by changluyi**
always_learn_from_arp_request: false
dynamic_neigh_routers: true
mac_binding_age_threshold: 300

# Pull Request

- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR

Examples of user facing changes:

- Features
- Bug fixes
- Docs
- Tests
https://github.com/kubeovn/kube-ovn/issues/4604

the fix is refer to  https://bugs.launchpad.net/neutron/+bug/1946318

## Which issue(s) this PR fixes

Fixes #4604

### CODE REVIEW

File: pkg/controller/init.go [hunk 1]
```diff
@@ -206,7 +206,25 @@ func (c *Controller) initNodeSwitch() error {
...
+	}
+
+	lr, err := c.OVNNbClient.GetLogicalRouter(c.config.ClusterRouter, false)
+	if err != nil {
+		klog.Errorf("get logical router %s failed: %v", c.config.ClusterRouter, err)
+		return err
+	}
+
+	lr.Options = map[string]string{"always_learn_from_arp_request": "false", "dynamic_neigh_routers": "true", "mac_binding_age_threshold": "300"}
+	err = c.OVNNbClient.UpdateLogicalRouter(lr)
```
Comment (zhangzujian) [inline pkg/controller/init.go:221]: 这里少了参数吧？

Comment (zhangzujian) [reply pkg/controller/init.go:221]: 还是都加上 fields 参数吧，如果多个用法之间有差别，很容易搞混淆。

Comment (changluyi) [reply pkg/controller/init.go]: ok

**Review by zhangzujian — APPROVED** [review]
