### PR TITLE
release vm ip when vm is stopped then deleted

### LINKED ISSUE #5367: [BUG] ip address leaked when VMs are stopped and deleted
### Kube-OVN Version

v1.13.3

### Kubernetes Version

v1.32.2

### Operation-system/Kernel Version

SUSE openleap 15.5 5.14.21-150500.55.97-default

### Description

V4UsingIPs count is not decremented when VMs are stopped and then deleted.
V4UsingIPs count is decremented when VMs are deleted.

Looks like kubeovn manages the ip address usage from ippool of subnets using pod creation and pod deletion events.

If the VM is stopped, the corresponding pod is removed, later when it is deleted, kubeovn will not be able to handle the vm delete event due to which V4UsingIPs is not decremented on the subnet status and ip addresses are leaked.

Also the subnet cannot be deleted as V4UsingIPs is still not zero.

### Steps To Reproduce

1.Create a subnet with provider p1
2.Create a VM and attach to provider p1 (network attachment definition)
3.stop the VM and check V4UsingIPs count on subnet status and it should stay intact (working as expected)
4.Now delete the VM
5.Expected behaviour
V4UsingIPs on subnet status must be zero
Actual behaviour
V4UsingIPs on subnet status is 1

4.check the during new VM creation:

I0617 17:30:10.995160       7 pod.go:227] enqueue add pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:30:10.995211       7 pod.go:450] handle add/update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:30:10.999384       7 pod.go:501] sync pod default/virt-launcher-vswitch1vm-mpcf2 allocated
I0617 17:30:10.999484       7 ipam.go:61] allocate v4 172.20.10.5, v6 , mac be:5b:ad:0d:e2:eb for default/vswitch1vm from subnet vswitch1
I0617 17:30:11.034390       7 ipam.go:61] allocate v4 10.52.1.198, v6 , mac b6:8a:08:02:11:73 for default/vswitch1vm from subnet ovn-default
I0617 17:30:11.042840       7 pod.go:395] enqueue update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:30:11.054802       7 pod.go:395] enqueue update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:30:11.085722       7 pod.go:450] handle add/update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:30:11.092806       7 pod.go:395] enqueue update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:30:11.092892       7 pod.go:450] handle add/update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:30:21.547713       7 node.go:503] handle update node vxlan-dev-1
I0617 17:30:40.648074       7 node.go:503] handle update node vxlan-dev-3
I0617 17:30:45.122618       7 pod.go:395] enqueue update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:30:45.122665       7 pod.go:450] handle add/update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:30:45.125333       7 pod.go:671] sync pod default/virt-launcher-vswitch1vm-mpcf2 routed
I0617 17:30:45.158213       7 pod.go:395] enqueue update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:30:45.158264       7 pod.go:450] handle add/update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:30:45.172313       7 pod.go:395] enqueue update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:30:45.172364       7 pod.go:450] handle add/update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:30:46.460333       7 node.go:503] handle update node vxlan-dev-1
I0617 17:31:33.488162       7 gc.go:386] gc logical switch port vm1-vswitch1.default.vswitch1.default.ovn
I0617 17:31:33.488924       7 ovn-nb-logical_switch_port.go:835] delete logical switch port vm1-vswitch1.default.vswitch1.default.ovn with id ad08c68a-0b4e-489e-97f1-d5ff126283a1 from logical switch vswitch1
I0617 17:31:33.498865       7 gc.go:401] gc ip vm1-vswitch1.default.vswitch1.default.ovn
I0617 17:31:33.507429       7 subnet.go:513] release v4 172.20.10.4 mac 42:84:71:af:40:46 from subnet vswitch1 for default/vm1-vswitch1, add ip to released list
I0617 17:31:33.507463       7 gc.go:386] gc logical switch port vm1-vswitch1.default
I0617 17:31:33.507834       7 ip.go:218] handle deleting ip vm1-vswitch1.default.vswitch1.default.ovn
I0617 17:31:33.508031       7 ip.go:251] ip cr vm1-vswitch1.default.vswitch1.default.ovn release ipam pod key default/vm1-vswitch1 from subnet vswitch1
I0617 17:31:33.508067       7 ovn-nb-logical_switch_port.go:835] delete logical switch port vm1-vswitch1.default with id 2678e5e7-510e-4a7b-8b8f-69a5bea534c0 from logical switch ovn-default
I0617 17:31:33.514952       7 ip.go:263] deleting ip vm1-vswitch1.default.vswitch1.default.ovn enqueue update status subnet vswitch1
I0617 17:31:33.516359       7 gc.go:401] gc ip vm1-vswitch1.default
I0617 17:31:33.525081       7 subnet.go:513] release v4 10.52.1.197 mac f2:01:02:5e:0a:c3 from subnet ovn-default for default/vm1-vswitch1, add ip to released list
I0617 17:31:33.525221       7 ip.go:218] handle deleting ip vm1-vswitch1.default
I0617 17:31:33.525460       7 ip.go:251] ip cr vm1-vswitch1.default release ipam pod key default/vm1-vswitch1 from subnet ovn-default
I0617 17:31:33.531860       7 ip.go:263] deleting ip vm1-vswitch1.default enqueue update status subnet ovn-default
I0617 17:31:39.062556       7 pod.go:395] enqueue update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:31:39.062607       7 pod.go:450] handle add/update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:31:39.336878       7 pod.go:395] enqueue update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:31:39.336952       7 pod.go:450] handle add/update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:31:40.619046       7 node.go:503] handle update node vxlan-dev-2
I0617 17:31:40.777942       7 pod.go:395] enqueue update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:31:40.777999       7 pod.go:450] handle add/update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:31:40.826234       7 pod.go:395] enqueue update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:31:40.826292       7 pod.go:450] handle add/update pod default/virt-launcher-vswitch1vm-mpcf2

during stopping the VM:

I0617 17:35:20.251087       7 pod.go:395] enqueue update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:35:20.251172       7 pod.go:450] handle add/update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:35:36.406964       7 pod.go:395] enqueue update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:35:36.407016       7 pod.go:450] handle add/update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:35:36.524774       7 pod.go:395] enqueue update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:35:36.524833       7 pod.go:450] handle add/update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:35:37.203710       7 pod.go:395] enqueue update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:35:37.203795       7 pod.go:450] handle add/update pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:35:37.203830       7 pod.go:257] enqueue delete pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:35:37.203855       7 pod.go:890] handle delete pod default/virt-launcher-vswitch1vm-mpcf2
I0617 17:35:37.204840       7 pod.go:949] handle deletion of vm pod vswitch1vm
I0617 17:35:37.213196       7 pod.go:952] try keep ip for vm pod default/vswitch1vm

kubectl get subnets
NAME          PROVIDER               VPC           VLAN   PROTOCOL   CIDR             PRIVATE   NAT     DEFAULT   GATEWAYTYPE   V4USED   V4AVAILABLE   V6USED   V6AVAILABLE   EXCLUDEIPS        U2OINTERCONNECTIONIP
join          ovn                    ovn-cluster          IPv4       100.64.0.0/16    false     false   false                   3        65530         0        0             ["100.64.0.1"]    
ovn-default   ovn                    ovn-cluster          IPv4       10.52.0.0/16     false     true    true      distributed   92       65441         0        0             ["10.52.0.1"]     
vswitch1      vswitch1.default.ovn   commonvpc            IPv4       172.20.10.0/24   false     false   false                   1        252           0        0             ["172.20.10.1"]   

during delete the VM:

ovn-controller did not receive any notification during VM deletion (no logs during this time)

======================================================================================================

create new VM:

I0617 17:45:23.723529       7 pod.go:227] enqueue add pod default/virt-launcher-vm1-new-kt6f6
I0617 17:45:23.723585       7 pod.go:450] handle add/update pod default/virt-launcher-vm1-new-kt6f6
I0617 17:45:23.729274       7 pod.go:501] sync pod default/virt-launcher-vm1-new-kt6f6 allocated
I0617 17:45:23.729341       7 ipam.go:61] allocate v4 172.20.10.6, v6 , mac 2a:f9:69:37:d9:c3 for default/vm1-new from subnet vswitch1
I0617 17:45:23.752113       7 pod.go:395] enqueue update pod default/virt-launcher-vm1-new-kt6f6
I0617 17:45:23.764976       7 ipam.go:61] allocate v4 10.52.1.199, v6 , mac 7a:fa:58:5c:9f:d1 for default/vm1-new from subnet ovn-default
I0617 17:45:23.773012       7 pod.go:395] enqueue update pod default/virt-launcher-vm1-new-kt6f6
I0617 17:45:23.800694       7 pod.go:450] handle add/update pod default/virt-launcher-vm1-new-kt6f6
I0617 17:45:23.808460       7 pod.go:395] enqueue update pod default/virt-launcher-vm1-new-kt6f6
I0617 17:45:23.808507       7 pod.go:450] handle add/update pod default/virt-launcher-vm1-new-kt6f6
I0617 17:45:28.737722       7 pod.go:395] enqueue update pod default/virt-launcher-vm1-new-kt6f6
I0617 17:45:28.737773       7 pod.go:450] handle add/update pod default/virt-launcher-vm1-new-kt6f6
I0617 17:45:28.740744       7 pod.go:671] sync pod default/virt-launcher-vm1-new-kt6f6 routed
I0617 17:45:28.780751       7 pod.go:395] enqueue update pod default/virt-launcher-vm1-new-kt6f6
I0617 17:45:28.780800       7 pod.go:450] handle add/update pod default/virt-launcher-vm1-new-kt6f6
I0617 17:45:28.800843       7 pod.go:395] enqueue update pod default/virt-launcher-vm1-new-kt6f6
I0617 17:45:28.800892       7 pod.go:450] handle add/update pod default/virt-launcher-vm1-new-kt6f6
I0617 17:45:29.754553       7 node.go:503] handle update node vxlan-dev-1
I0617 17:45:39.724361       7 node.go:503] handle update node vxlan-dev-1
I0617 17:46:14.125917       7 node.go:503] handle update node vxlan-dev-2
I0617 17:46:19.693538       7 pod.go:395] enqueue update pod default/virt-launcher-vm1-new-kt6f6
I0617 17:46:19.693591       7 pod.go:450] handle add/update pod default/virt-launcher-vm1-new-kt6f6
I0617 17:46:20.102262       7 pod.go:395] enqueue update pod default/virt-launcher-vm1-new-kt6f6
I0617 17:46:20.102304       7 pod.go:450] handle add/update pod default/virt-launcher-vm1-new-kt6f6
I0617 17:46:22.286556       7 pod.go:395] enqueue update pod default/virt-launcher-vm1-new-kt6f6
I0617 17:46:22.286598       7 pod.go:450] handle add/update pod default/virt-launcher-vm1-new-kt6f6
I0617 17:46:22.342840       7 pod.go:395] enqueue update pod default/virt-launcher-vm1-new-kt6f6
I0617 17:46:22.342887       7 pod.go:450] handle add/update pod default/virt-launcher-vm1-new-kt6f6
I0617 17:46:39.919390       7 node.go:503] handle update node vxlan-dev-3
I0617 17:47:45.788750       7 node.go:503] handle update node vxlan-dev-2
I0617 17:47:49.180742       7 node.go:503] handle update node vxlan-dev-1
I0617 17:48:34.868143       7 node.go:503] handle update node vxlan-dev-3

kubectl get subnets
NAME          PROVIDER               VPC           VLAN   PROTOCOL   CIDR             PRIVATE   NAT     DEFAULT   GATEWAYTYPE   V4USED   V4AVAILABLE   V6USED   V6AVAILABLE   EXCLUDEIPS        U2OINTERCONNECTIONIP
join          ovn                    ovn-cluster          IPv4       100.64.0.0/16    false     false   false                   3        65530         0        0             ["100.64.0.1"]    
ovn-default   ovn                    ovn-cluster          IPv4       10.52.0.0/16     false     true    true      distributed   92       65441         0        0             ["10.52.0.1"]     
vswitch1      vswitch1.default.ovn   commonvpc            IPv4       172.20.10.0/24   false     false   false                   1        252           0        0             ["172.20.10.1"]   

delete directly without stopping the VMs
========================================

kubectl get subnets
NAME          PROVIDER               VPC           VLAN   PROTOCOL   CIDR             PRIVATE   NAT     DEFAULT   GATEWAYTYPE   V4USED   V4AVAILABLE   V6USED   V6AVAILABLE   EXCLUDEIPS        U2OINTERCONNECTIONIP
join          ovn                    ovn-cluster          IPv4       100.64.0.0/16    false     false   false                   3        65530         0        0             ["100.64.0.1"]    
ovn-default   ovn                    ovn-cluster          IPv4       10.52.0.0/16     false     true    true      distributed   91       65442         0        0             ["10.52.0.1"]     
vswitch1      vswitch1.default.ovn   commonvpc            IPv4       172.20.10.0/24   false     false   false                   0        253           0        0             ["172.20.10.1"]   

17:48:55.761426       7 node.go:503] handle update node vxlan-dev-1
I0617 17:49:29.240806       7 node.go:503] handle update node vxlan-dev-2
I0617 17:49:33.664442       7 gc.go:386] gc logical switch port vswitch1vm.default.vswitch1.default.ovn
I0617 17:49:33.665076       7 ovn-nb-logical_switch_port.go:835] delete logical switch port vswitch1vm.default.vswitch1.default.ovn with id 4ec3e0de-b7fa-4f00-a686-d578969994da from logical switch vswitch1
I0617 17:49:33.677348       7 gc.go:401] gc ip vswitch1vm.default.vswitch1.default.ovn
I0617 17:49:33.685420       7 subnet.go:513] release v4 172.20.10.5 mac be:5b:ad:0d:e2:eb from subnet vswitch1 for default/vswitch1vm, add ip to released list
I0617 17:49:33.685447       7 gc.go:386] gc logical switch port vswitch1vm.default
I0617 17:49:33.685775       7 ip.go:218] handle deleting ip vswitch1vm.default.vswitch1.default.ovn
I0617 17:49:33.685956       7 ip.go:251] ip cr vswitch1vm.default.vswitch1.default.ovn release ipam pod key default/vswitch1vm from subnet vswitch1
I0617 17:49:33.686024       7 ovn-nb-logical_switch_port.go:835] delete logical switch port vswitch1vm.default with id d6545ba9-6254-4c9a-9932-ac38479c3436 from logical switch ovn-default
I0617 17:49:33.693297       7 ip.go:263] deleting ip vswitch1vm.default.vswitch1.default.ovn enqueue update status subnet vswitch1
I0617 17:49:33.695237       7 gc.go:401] gc ip vswitch1vm.default
I0617 17:49:33.708356       7 subnet.go:513] release v4 10.52.1.198 mac b6:8a:08:02:11:73 from subnet ovn-default for default/vswitch1vm, add ip to released list
I0617 17:49:33.708557       7 ip.go:218] handle deleting ip vswitch1vm.default
I0617 17:49:33.708846       7 ip.go:251] ip cr vswitch1vm.default release ipam pod key default/vswitch1vm from subnet ovn-default
I0617 17:49:33.715052       7 ip.go:263] deleting ip vswitch1vm.default enqueue update status subnet ovn-default
I0617 17:50:05.186866       7 pod.go:1973] vm vm1-new is deleting
I0617 17:50:21.882515       7 pod.go:1973] vm vm1-new is deleting
I0617 17:50:22.023179       7 pod.go:1973] vm vm1-new is deleting
I0617 17:50:22.572305       7 node.go:503] handle update node vxlan-dev-1
I0617 17:50:22.617626       7 pod.go:1973] vm vm1-new is deleting
I0617 17:50:22.617777       7 pod.go:257] enqueue delete pod default/virt-launcher-vm1-new-kt6f6
I0617 17:50:22.617824       7 pod.go:890] handle delete pod default/virt-launcher-vm1-new-kt6f6
I0617 17:50:22.618925       7 pod.go:949] handle deletion of vm pod vm1-new
I0617 17:50:22.629319       7 pod.go:1973] vm vm1-new is deleting
I0617 17:50:22.668484       7 pod.go:1030] delete logical switch port vm1-new.default.vswitch1.default.ovn
I0617 17:50:22.669101       7 ovn-nb-logical_switch_port.go:835] delete logical switch port vm1-new.default.vswitch1.default.ovn with id 6e742bac-d87e-4459-b3e5-4be3a6ca2d32 from logical switch vswitch1
I0617 17:50:22.675177       7 pod.go:1030] delete logical switch port vm1-new.default
I0617 17:50:22.675818       7 ovn-nb-logical_switch_port.go:835] delete logical switch port vm1-new.default with id 82ac2f02-73e4-4368-8c26-81dd261efc12 from logical switch ovn-default
I0617 17:50:22.683420       7 pod.go:1036] try release all ip address for deleting pod default/vm1-new
I0617 17:50:22.683459       7 pod.go:1048] delete ip CR vm1-new.default.vswitch1.default.ovn
I0617 17:50:22.694610       7 subnet.go:513] release v4 172.20.10.6 mac 2a:f9:69:37:d9:c3 from subnet vswitch1 for default/vm1-new, add ip to released list
I0617 17:50:22.694656       7 pod.go:1048] delete ip CR vm1-new.default
I0617 17:50:22.694921       7 ip.go:218] handle deleting ip vm1-new.default.vswitch1.default.ovn
I0617 17:50:22.695208       7 ip.go:251] ip cr vm1-new.default.vswitch1.default.ovn release ipam pod key default/vm1-new from subnet vswitch1
I0617 17:50:22.700182       7 subnet.go:513] release v4 10.52.1.199 mac 7a:fa:58:5c:9f:d1 from subnet ovn-default for default/vm1-new, add ip to released list
I0617 17:50:22.702789       7 ip.go:218] handle deleting ip vm1-new.default
I0617 17:50:22.702895       7 ip.go:263] deleting ip vm1-new.default.vswitch1.default.ovn enqueue update status subnet vswitch1
I0617 17:50:22.703043       7 ip.go:251] ip cr vm1-new.default release ipam pod key default/vm1-new from subnet ovn-default
I0617 17:50:22.713100       7 ip.go:263] deleting ip vm1-new.default enqueue update status subnet ovn-default

### Current Behavior

V4UsingIPs on subnet status must be decremented when VMs are stopped and then deleted.

### Expected Behavior

4UsingIPs on subnet status not decremented when VMs are stopped and then deleted.

### PR DESCRIPTION
**Pull request by oilbeater**
# Pull Request

- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR

Examples of user facing changes:

- Bug fixes

## Which issue(s) this PR fixes

Fixes #5367

### CODE REVIEW

File: pkg/controller/kubevirt.go [hunk 1]
```diff
@@ -34,6 +35,44 @@ func (c *Controller) enqueueUpdateVMIMigration(oldObj, newObj any) {
...
+	c.deleteVMQueue.Add(key)
+}
+
+func (c *Controller) handleDeleteVM(key string) error {
+	namespace, name, err := cache.SplitMetaNamespaceKey(key)
+	if err != nil {
+		utilruntime.HandleError(fmt.Errorf("invalid vm key: %s", key))
+		return nil
+	}
+	podKey := fmt.Sprintf("%s/%s", namespace, name)
```
Comment (zbb88888) [inline pkg/controller/kubevirt.go]: 建议： 这个文件是不是都是 vm key 更好理解些

Comment (oilbeater) [reply pkg/controller/kubevirt.go]: 确实 vm key 更合适一些
