### PR TITLE
fix concurrent map race

### LINKED ISSUE #5410: [BUG] concurrent map iteration and map write
### Kube-OVN Version

v1.15.0

### Kubernetes Version

v1.32.6

### Operation-system/Kernel Version

---

### Description

kube-ovn-controller reports an error:

```log
I0630 06:11:56.069756      13 namespace.go:84] handle add/update namespace cert-manager
I0630 06:11:56.656010      13 endpoint_slice.go:66] handle update endpointSlice for service cert-manager/cert-manager-cainjector
I0630 06:11:56.662436      13 service.go:225] handle update service cert-manager/cert-manager-cainjector
I0630 06:11:56.662712      13 service.go:292] add vip 10.105.174.245:9402 to LB cluster-tcp-loadbalancer
I0630 06:11:56.662918      13 endpoint_slice.go:66] handle update endpointSlice for service cert-manager/cert-manager-cainjector
fatal error: concurrent map iteration and map write
```

### Steps To Reproduce

Run Webhook E2E test.

### Current Behavior

---

### Expected Behavior

---

### PR DESCRIPTION
**Pull request by cmdy**
# Pull Request

- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR

Examples of user facing changes:

- Features
- Bug fixes
- Docs
- Tests

## Which issue(s) this PR fixes

Fixes #5410

image

### CODE REVIEW

**Review by oilbeater — APPROVED** [review]

File: pkg/controller/subnet.go [hunk 1]
```diff
@@ -79,14 +79,11 @@ func (c *Controller) enqueueUpdateSubnet(oldObj, newObj any) {
 
 	if oldSubnet.Spec.Vpc != newSubnet.Spec.Vpc &&
 		((oldSubnet.Spec.Vpc != "" || newSubnet.Spec.Vpc != c.config.ClusterRouter) && (oldSubnet.Spec.Vpc != c.config.ClusterRouter || newSubnet.Spec.Vpc != "")) {
-		if newSubnet.Annotations == nil {
-			newSubnet.Annotations = make(map[string]string)
-		}
-
+		// recode last vpc name for subnet
```
Comment (zbb88888) [inline pkg/controller/subnet.go:82]: recode -->record ?

File: pkg/controller/vpc.go [hunk 2]
```diff
@@ -65,10 +65,8 @@ func (c *Controller) enqueueUpdateVpc(oldObj, newObj any) {
 		!slices.Equal(oldVpc.Status.Subnets, newVpc.Status.Subnets) {
 		// TODO:// label VpcExternalLabel replace with spec enable external
 
-		if newVpc.Annotations == nil {
-			newVpc.Annotations = make(map[string]string)
-		}
-		newVpc.Annotations[util.VpcLastPolicies] = convertPolicies(oldVpc.Spec.PolicyRoutes)
+		// recode last policies
```
Comment (zbb88888) [inline pkg/controller/vpc.go:68]: recode -->record ?

Comment (cmdy) [reply pkg/controller/vpc.go:68]: there need use "record" , we next pr fix it

Comment (zbb88888) [reply pkg/controller/vpc.go:68]: ok
