### PR TITLE
fix update dnat rules not effect correctly

### LINKED ISSUE #2517: the protocol, internal ip, external port and internal port of the dnat rule could not be updated correctly
# Expected Behavior

# Actual Behavior
While update the protocol, internal ip, external port, or internal port of the dnat rule, it will not really take effect in the vpc nat gateway pod, the rules k8s shows does not match the actual rule in gateway pod.

original
  ```
Chain SHARED_DNAT (1 references)
target     prot opt source               destination         
DNAT       6    --  0.0.0.0/0            100.71.45.104        tcp dpt:8880 to:192.168.5.7:80
  ```
  ```
NAME        EIP                     PROTOCOL   V4IP            V6IP   INTERNALIP     EXTERNALPORT   INTERNALPORT   NATGWDP       READY
cn-dnat01   eip-gw-cn-vpc02-eip03   tcp        100.71.45.104          192.168.5.7    8880           80             gw-cn-vpc02   true
  ```
updated
  ```
Chain SHARED_DNAT (1 references)
target     prot opt source               destination         
DNAT       6    --  0.0.0.0/0            100.71.45.104        tcp dpt:8888 to:192.168.5.7:80
  ```
  ```
NAME        EIP                     PROTOCOL   V4IP            V6IP   INTERNALIP     EXTERNALPORT   INTERNALPORT   NATGWDP       READY
cn-dnat01   eip-gw-cn-vpc02-eip03   tcp        100.71.45.104          192.168.5.7    8880           80             gw-cn-vpc02   true
  ```

# Steps to Reproduce the Problem

1.create eip && dnat
2.update the protocol, internal ip, external port, or internal port of the dnat rule

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

### PR DESCRIPTION
**Pull request by qiutingjun**
- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

#### What type of this PR
- Bug fixes

#### Which issue(s) this PR fixes:
Fixes #2517

### CODE REVIEW

**Review by bobz965 — APPROVED** [review]

File: pkg/controller/vpc_nat_gw_nat.go [hunk 1]
```diff
@@ -100,9 +101,21 @@ func (c *Controller) enqueueUpdateIptablesDnatRule(old, new interface{}) {
...
 		oldDnat.Spec.EIP != newDnat.Spec.EIP ||
-		oldDnat.Status.Redo != newDnat.Status.Redo {
+		oldDnat.Status.Redo != newDnat.Status.Redo ||
+		oldDnat.Spec.Protocol != newDnat.Spec.Protocol ||
+		oldDnat.Spec.InternalIp != newDnat.Spec.InternalIp ||
+		oldDnat.Spec.InternalPort != newDnat.Spec.InternalPort ||
+		oldDnat.Spec.ExternalPort != newDnat.Spec.ExternalPort {
 		klog.V(3).Infof("enqueue update dnat %s", key)
-		c.updateIptablesDnatRuleQueue.Add(key)
+		raw, _ := json.Marshal(map[string]string{
```
Comment (oilbeater) [inline pkg/controller/vpc_nat_gw_nat.go:110]: 最好还是把 key 加入队列，然后在 handle 的时候直接把所有规则 flush，或者差量更新。

**Review by oilbeater — CHANGES_REQUESTED** [review]

File: pkg/controller/vpc_nat_gw_nat.go (hunk 1 above)
Comment (qiutingjun) [reply pkg/controller/vpc_nat_gw_nat.go]: I've changed to store the information from the old version to status, so that when updating the rule, I could obtain last status information to delete the obsolete rules.

**Review by oilbeater — APPROVED** [review]
