### PR TITLE
speaker: add option to set node IP to override pod IP

### LINKED ISSUE #4139: [BUG] speaker: invalid next hop ip address when running pod without host network mode
### Kube-OVN Version

v1.12.16

### Kubernetes Version

v1.27.11

### Operation-system/Kernel Version

all kernels

### Description

When the speaker pod cannot run in host network mode, the default router ID and the source IP address of some routes is set to the pod IP, which is in a different subnet than the actual router IP address, causing invalid next hop IP address for those routes.

### Steps To Reproduce

- Run speaker with `hostNetwork: false`

### Current Behavior

Invalid next hop IP address for some routes which is the IP address of the pod 

### Expected Behavior

The IP address of the node should be set as the next hop for those routes

### PR DESCRIPTION
**Pull request by yaa110**
# Pull Request

- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR

- Features

Sometimes the speaker pod cannot run in host network mode, causing the default router ID and the source IP address of some routes to be set to the pod IP, which is in a different subnet than the actual router IP address. By introducing a new flag for the node IP, we can override the invalid router IP address.

## Which issue(s) this PR fixes

Fixes #4139

### CODE REVIEW

File: pkg/speaker/subnet.go [hunk 1]
```diff
@@ -348,11 +348,14 @@ func getNextHopFromPathAttributes(attrs []bgp.PathAttributeInterface) net.IP {
...
-	nextHop := routeID
+func (c *Controller) getNextHopAttribute(neighborAddress string) string {
+	nextHop := c.config.RouterID
 	routes, err := netlink.RouteGet(net.ParseIP(neighborAddress))
 	if err == nil && len(routes) == 1 && routes[0].Src != nil {
 		nextHop = routes[0].Src.String()
 	}
+	if c.config.NodeIP != "" && nextHop == c.config.PodIP {
+		nextHop = c.config.NodeIP
+	}
```
Comment (zhangzujian) [inline pkg/speaker/subnet.go:359]: We should consider deployment in duak-stack clusters.

Comment (yaa110) [reply pkg/speaker/subnet.go]: done

File: pkg/speaker/subnet.go [hunk 2]
```diff
@@ -348,11 +348,18 @@ func getNextHopFromPathAttributes(attrs []bgp.PathAttributeInterface) net.IP {
...
 	if err == nil && len(routes) == 1 && routes[0].Src != nil {
 		nextHop = routes[0].Src.String()
 	}
+	proto := util.CheckProtocol(nextHop)
+	nextHopIP := net.ParseIP(nextHop)
+	nodeIP := c.config.NodeIPs[proto]
+	podIP := c.config.PodIPs[proto]
+	if nodeIP != nil && podIP != nil && nextHopIP != nil && nextHopIP.Equal(podIP) {
+		nextHop = nodeIP.String()
+	}
```
Comment (zhangzujian) [inline pkg/speaker/subnet.go:363]: I think we should use nodeIP as nextHtop if the nodeIP is not nil. No need to check podIP.

Comment (yaa110) [reply pkg/speaker/subnet.go]: done

File: pkg/speaker/subnet.go [hunk 3]
```diff
@@ -348,11 +348,17 @@ func getNextHopFromPathAttributes(attrs []bgp.PathAttributeInterface) net.IP {
 	return nil
 }
 
-func getNextHopAttribute(neighborAddress, routeID string) string {
-	nextHop := routeID
+func (c *Controller) getNextHopAttribute(neighborAddress string) string {
```
Comment (zhangzujian) [inline pkg/speaker/subnet.go:351]: I mean this function should be like this:

```go
func (c *Controller) getNextHopAttribute(neighborAddress string) string {
	proto := util.CheckProtocol(neighborAddress)
	if nodeIP := c.config.NodeIPs[proto]; nodeIP != nil {
		return nodeIP.String()
	}

	nextHop := c.config.RouterID
	routes, err := netlink.RouteGet(net.ParseIP(neighborAddress))
	if err == nil && len(routes) == 1 && routes[0].Src != nil {
		nextHop = routes[0].Src.String()
	}
	return nextHop
}
```

Comment (yaa110) [reply pkg/speaker/subnet.go:351]: what if the route has a different source from the podIP? I meant, we should only use nodeIP when the nextHop equals podIP.
