### PR TITLE
fix: multus macvlan ipvlan use kube-ovn ipam，but  ip not inited in init-ipam

### LINKED ISSUE #1840: Multi Pod use one same ip, which cause network problems
# Expected Behavior
different pod nic in one subnet should use different ip

# Actual Behavior
multi pod net1 nic use the same ip， eip also use the same ip。
ip allocate from  ovn-vpc-external-network

``` bash

[root@hci-ctrl-1 ~]# kubectl  get fip | grep 10.122.193.49
qa-ygsp.sfu-mc-1-01-shanghai                                    qa-ygsp.sfu-mc-1-01-shanghai                                    10.122.193.49    10.116.27.38            true    yealink-shanghai-pod
[root@hci-ctrl-1 ~]# 
[root@hci-ctrl-1 ~]# kubectl  get ip |grep 10.122.193.49
vpc-nat-gw-yealink-hangzhou-pod-5fb7497ddb-m64hd.kube-system.ovn-vpc-external-network.kube-system        10.122.193.49           00:00:00:77:74:4B   hci-compute-xnet-6   ovn-vpc-external-network
vpc-nat-gw-yealink-observability-pod-76c5fd8974-m479v.kube-system.ovn-vpc-external-network.kube-system   10.122.193.49           00:00:00:97:84:2C   hci-compute-xnet-4   ovn-vpc-external-network



# as you see， ipam allocate the same ip to 2 ips for pod，and 1 eip for fip


# log shows 

/var/log/kube-ovn/kube-ovn-controller.log:I0823 08:48:50.653333       7 ipam.go:51] allocate v4 10.122.193.49 v6  mac 00:00:00:93:D9:61 for qa-ygsp.sfu-mc-1-01-shanghai
/var/log/kube-ovn/kube-ovn-controller.log:I0823 09:28:16.873086       7 subnet.go:453] release v4 10.122.193.49 mac 00:00:00:93:D9:61 for qa-ygsp.sfu-mc-1-01-shanghai, add ip to released list



# as you can see eip still get the same ip today 0823,   

# and the same ip allocate to nat gw pod net1 nic at  "2022-07-26T01:48:43Z"



[root@hci-ctrl-1 ~]# kubectl  get ip vpc-nat-gw-yealink-observability-pod-76c5fd8974-m479v.kube-system.ovn-vpc-external-network.kube-system -o yaml
apiVersion: kubeovn.io/v1
kind: IP
metadata:
  creationTimestamp: "2022-07-26T01:48:43Z"
  generation: 2
  labels:
    ovn-vpc-external-network: ""
    ovn.kubernetes.io/subnet: ovn-vpc-external-network
  name: vpc-nat-gw-yealink-observability-pod-76c5fd8974-m479v.kube-system.ovn-vpc-external-network.kube-system
  resourceVersion: "12545586"
  uid: e6ebe5f8-bcab-4f38-9cbb-2cb72ac5bb14
spec:
  attachIps: []
  attachMacs: []
  attachSubnets: []
  containerID: ""
  ipAddress: 10.122.193.49
  macAddress: 00:00:00:97:84:2C
  namespace: kube-system
  nodeName: hci-compute-xnet-4
  podName: vpc-nat-gw-yealink-observability-pod-76c5fd8974-m479v
  podType: ""
  subnet: ovn-vpc-external-network
  v4IpAddress: 10.122.193.49
  v6IpAddress: ""







[root@hci-ctrl-1 ~]# kubectl  get po -A -o wide | grep kube-ovn-control
kube-system            kube-ovn-controller-6d4dfc9678-5k4z8                              1/1     Running   29 (3d18h ago)   34d     10.122.16.44    hci-compute-xnet-4   <none>           <none>
kube-system            kube-ovn-controller-6d4dfc9678-gr58f                              1/1     Running   30 (7d1h ago)    34d     10.122.16.43    hci-compute-xnet-3   <none>           <none>
kube-system            kube-ovn-controller-6d4dfc9678-p6r96                              1/1     Running   25 (24h ago)     34d     10.122.16.46    hci-compute-xnet-6   <none>           <none>



# as you can see， ovn-controller crashed  1-2 day/ one time

i guess maybe ipam allocate ip during ipam recovery process, 



```

``` 历史 log 分析

[root@hci-compute-xnet-6 kube-ovn]# grep -v vpc_nat -r kube-ovn-controller.log.1 > /tmp/test.log
[root@hci-compute-xnet-6 kube-ovn]# vi /tmp/test.log
[root@hci-compute-xnet-6 kube-ovn]# 
[root@hci-compute-xnet-6 kube-ovn]# 
[root@hci-compute-xnet-6 kube-ovn]# 
[root@hci-compute-xnet-6 kube-ovn]# grep  10.122.193.49 /tmp/test.log
[root@hci-compute-xnet-6 kube-ovn]# mv /tmp/test.log /tmp/0822-0823-kube-ovn-controller-crashed-reinit-ipam-lost-10.122.193.49-ip.log


去除上次kube-ovn-controller重启时间点的log，去除无关的nat-gw  相关的业务没处理好的err log

[root@hci-compute-xnet-6 kube-ovn]# grep -v vpc_nat -r kube-ovn-controller.log.1 > /tmp/test.log
[root@hci-compute-xnet-6 kube-ovn]# vi /tmp/test.log
[root@hci-compute-xnet-6 kube-ovn]# 
[root@hci-compute-xnet-6 kube-ovn]# 
[root@hci-compute-xnet-6 kube-ovn]# 
[root@hci-compute-xnet-6 kube-ovn]# grep  10.122.193.49 /tmp/test.log
[root@hci-compute-xnet-6 kube-ovn]# mv /tmp/test.log /tmp/0822-0823-kube-ovn-controller-crashed-reinit-ipam-lost-10.122.193.49-ip.log


这里 10.122.193.49 pod net1使用的 ip 没看到被初始化



```

# Steps to Reproduce the Problem

1. create nat-gw pod
2. create eip (fip )
3. repeate (let kube-ovn-controller crashed during the process)

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
[root@hci-ctrl-1 ~]# kubectl  version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:30:55Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:24:41Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
  ```

- kube-ovn version:
  
  ```
kube-ovn:v1.10.0

  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
[root@hci-ctrl-1 ~]# awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release
"CentOS Stream 8"

[root@hci-ctrl-1 ~]# uname -r
5.4.205-1.el8.elrepo.x86_64

  ```

### PR DESCRIPTION
**Pull request by bobz965**
- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

#### What type of this PR

- Bug fixes

fix: multus macvlan ipvlan use kube-ovn ipam，but  ip not inited in init-ipam
1. fix: ip-list-recovery-ipam skips all non StatefulSet ip and pod-list-recovery-ipam skips non-ovn subnet, which cause nat-gw-pod (other cni using kube-ovn ipam, such as macvlan,ipvlan) lost ipam after kube-ovn-controller crashed

经沟通，大多数ip ipam恢复的数据源以pod为准，ip list 只处理sts ip（包含join ip和业务sts pod ip）

#### Which issue(s) this PR fixes:
Fixes #1840

### CODE REVIEW

File: pkg/controller/init.go [hunk 1]
```diff
@@ -364,38 +365,33 @@ func (c *Controller) InitIPAM() error {
 		podName := c.getNameByPod(pod)
 		key := fmt.Sprintf("%s/%s", pod.Namespace, podName)
 		for _, podNet := range podNets {
-			if !isOvnSubnet(podNet.Subnet) {
-				continue
```
Comment (hongzhen-ma) [inline pkg/controller/init.go:368]: 是不是把这个地方，ovn 子网的检查去掉，就能包含attach-net-def 子网的恢复了？

**Review by hongzhen-ma — APPROVED** [review]

**Review by hongzhen-ma — APPROVED** [review]

**Comment by hongzhen-ma** [comment]
已回合 release-1.10  releas-1.9 和 release-1.8 分支
