### PR TITLE
fix: put iptables nat prerouting rule right before kube-proxy inserted one

### LINKED ISSUE #5078: [BUG] cni initialisation fails
### Kube-OVN Version

v1.13.3

### Kubernetes Version

v1.31.4

### Operation-system/Kernel Version

Harvester (based on SLE Micro 5.5)

### Description

CNI initialisation fails with following error

```
I0313 04:47:48.478768    5084 gateway_linux.go:441] the first nat prerouting rule is ["-m" "comment" "--comment" "kube-ovn prerouting rules" "-j" "OVN-PREROUTING"]
W0313 04:47:48.478848    5084 gateway_linux.go:454] delete the nat prerouting rule: {nat PREROUTING 3 [-m comment --comment kube-ovn prerouting rules -j OVN-PREROUTING]}
I0313 04:47:48.478869    5084 gateway_linux.go:1074] delete iptables rule by pos 3: {nat PREROUTING 3 [-m comment --comment kube-ovn prerouting rules -j OVN-PREROUTING]}
W0313 04:47:48.481882    5084 gateway_linux.go:454] delete the nat prerouting rule: {nat PREROUTING 4 [-m comment --comment kube-ovn prerouting rules -j OVN-PREROUTING]}
I0313 04:47:48.481912    5084 gateway_linux.go:1074] delete iptables rule by pos 4: {nat PREROUTING 4 [-m comment --comment kube-ovn prerouting rules -j OVN-PREROUTING]}
W0313 04:47:48.485737    5084 gateway_linux.go:454] delete the nat prerouting rule: {nat PREROUTING 5 [-m comment --comment kube-ovn prerouting rules -j OVN-PREROUTING]}
I0313 04:47:48.485768    5084 gateway_linux.go:1074] delete iptables rule by pos 5: {nat PREROUTING 5 [-m comment --comment kube-ovn prerouting rules -j OVN-PREROUTING]}
E0313 04:47:48.488290    5084 gateway_linux.go:1076] failed to delete iptables PREROUTING rule "-m comment --comment kube-ovn prerouting rules -j OVN-PREROUTING": running [/usr/local/sbin/iptables -t nat -D PREROUTING 5 --wait]: exit status 1: iptables: Index of deletion too big.
E0313 04:47:48.488367    5084 gateway_linux.go:456] failed to delete rule {nat PREROUTING 5 [-m comment --comment kube-ovn prerouting rules -j OVN-PREROUTING]}: running [/usr/local/sbin/iptables -t nat -D PREROUTING 5 --wait]: exit status 1: iptables: Index of deletion too big.
```

I believe this is being caused by the changes in `gateway_linux.go`  https://github.com/kubeovn/kube-ovn/blob/master/pkg/daemon/gateway_linux.go#L455

When deleting the rule we are iterating over rules but deletion of a rule shifts the remaining rule position up, and eventually we end up trying to delete a rule at a non existent position 

### Steps To Reproduce

1. Install rke2 v1.31.4
2. Install kubeovn v1.13.3
3. CNI initialisation fails

### Current Behavior

CNI fails to initialise

### Expected Behavior

CNI should initialise correctly

### PR DESCRIPTION
**Pull request by starbops**
# Pull Request

- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR

Examples of user facing changes:

- Bug fixes

I'm unsure if this is a bug fix or not since Kube-OVN does not support running along with other CNI plug-ins. But we do have such use cases that using the Multus CNI to consume both Calico/Canal and Kube-OVN to bring advance networking feature to VMs running on Harvester.

Previously, we found contention in iptables rules, especially the NAT PREROUTING chain. Calico/Canal is competing with Kube-OVN to insert its rules at the top of the chain. After checking the original issue that made the Kube-OVN rule the top-most rule in the NAT PREROUTING chain, we found that it might not be necessary to be that aggressive. The real problem was that the Kube-OVN inserted rule falls behind the kube-proxy rule, so we just need to make the rule have a higher priority than the kube-proxy one. Fighting for the top position causes unnecessary headaches and blocks the potential to work with other CNI plug-ins.

This PR tries to put the Kube-OVN rule `-m comment --comment "kube-ovn prerouting rules" -j OVN-PREROUTING` in the correct slot in the NAT PREROUTING chain. It ensures the rule has a higher priority than the kube-proxy rule `-m comment --comment "kubernetes service portals" -j KUBE-SERVICES` but not necessarily the top-most one. When duplicated Kube-OVN rules exist in the chain, it will delete them.

## Which issue(s) this PR fixes

Fixes #5078

### CODE REVIEW

**Comment by starbops** [comment]
Hi @zhangzujian and @oilbeater, would you mind taking a look at this? Please let me know if there's anything I can do to improve this and move it forward. Thank you very much!

File: pkg/daemon/gateway_linux.go [hunk 1]
```diff
@@ -415,6 +415,104 @@ func (c *Controller) deletePolicyRouting(family int, _ string, priority, tableID
...
+// Returns all matching position indices, or an empty slice if none found.
+func findRulePositions(ipt *iptables.IPTables, rule util.IPTableRule) ([]int, error) {
+	rules, err := ipt.List(rule.Table, rule.Chain)
+	if err != nil {
+		return nil, fmt.Errorf("failed to list iptables rules: %w", err)
+	}
+
+	positions := make([]int, 0)
+
+	// Start from the end of the list (lowest priority) and go up to 1 (but skip index 0)
```
Comment (oilbeater) [inline pkg/daemon/gateway_linux.go:429]: Why skip 0 here?

File: pkg/daemon/gateway_linux.go [hunk 2]
```diff
@@ -415,6 +415,104 @@ func (c *Controller) deletePolicyRouting(family int, _ string, priority, tableID
...
+		insertPosition = kubeProxyPosList[len(kubeProxyPosList)-1]
+	}
+
+	// Check if the rule already exists at a higher priority than the kube-proxy rule
+	existingNatPreroutingPosList, err := findRulePositions(ipt, rule)
+	if err != nil {
+		return fmt.Errorf("failed to find nat prerouting rule position: %w", err)
+	}
+	if len(existingNatPreroutingPosList) > 0 {
+		for _, pos := range existingNatPreroutingPosList {
```
Comment (oilbeater) [inline pkg/daemon/gateway_linux.go:467]: Can we use `pos < existingNatPreroutingPosList[len(existingNatPreroutingPosList) -1]` to simplify this logical.

File: pkg/daemon/gateway_linux.go [hunk 3]
```diff
@@ -415,6 +415,104 @@ func (c *Controller) deletePolicyRouting(family int, _ string, priority, tableID
...
+func ensureNatPreroutingRuleNoDuplicate(ipt *iptables.IPTables, rule util.IPTableRule) error {
+	existingNatPreroutingPosList, err := findRulePositions(ipt, rule)
+	if err != nil {
+		return fmt.Errorf("failed to find nat prerouting rule position: %w", err)
+	}
+	if len(existingNatPreroutingPosList) == 0 {
+		klog.Warningf("nat prerouting rule not found, skipping duplicate check")
+		return nil
+	}
+
```
Comment (oilbeater) [inline pkg/daemon/gateway_linux.go:489]: There is still a possibility that the iptables index will change between findRulePositions and the deletion/insertion of rules if Calico or other network operators insert rules at the same time. I looked through the go-iptables library but couldn't find any locking or transaction mechanism, so we may need to accept this limitation.

**Review by oilbeater — CHANGES_REQUESTED** [review]

File: pkg/daemon/gateway_linux.go (hunk 1 above)
Comment (starbops) [reply pkg/daemon/gateway_linux.go:429]: The rule at index zero would be the policy rule. This was also omitted in the original code snippet. I just follow the spirit here.

File: pkg/daemon/gateway_linux.go (hunk 2 above)
Comment (starbops) [reply pkg/daemon/gateway_linux.go]: Nice suggestion. I'll update it.

File: pkg/daemon/gateway_linux.go (hunk 3 above)
Comment (starbops) [reply pkg/daemon/gateway_linux.go:485]: Yes, it is unfortunately possible. I can add comments to state the limitation. FWIW, this would not bring damage when it comes to rule insertion, because the controller remove the duplicates later on.

**Comment by starbops** [comment]
@oilbeater Thank you for your kind review. Please take a look at the revised version.

**Comment by oilbeater** [comment]
Thanks! @starbops
