### PR TITLE
do not delete external switch if it is created by provider network vlan subnet

### LINKED ISSUE #2446: If the value of enable-external-gw is false,  emcp route still exists
# Expected Behavior
The bfd emcp function can be disabled

# Actual Behavior
enable-external-gw is false， emcp route still exists
```
# k ko  nbctl lr-route-list vpc1
IPv4 Routes
Route Table <main>:
           192.168.0.0/24              10.5.204.103 src-ip ecmp ecmp-symmetric-reply bfd
           192.168.0.0/24              10.5.204.104 src-ip ecmp ecmp-symmetric-reply bfd
           192.168.0.0/24              10.5.204.105 src-ip ecmp ecmp-symmetric-reply bfd
                0.0.0.0/0             192.168.0.254 dst-ip

```

# Steps to Reproduce the Problem

1.`enableBfd: true` and `enableExternal: true` in subnet
2. `enable-external-gw: "true"` in cm ovn-external-gw-config
3.  `enable-external-gw: "false"` in cm ovn-external-gw-config

### PR DESCRIPTION
**Pull request by bobz965**
- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

#### What type of this PR

- 避免ovn默认vpc不再使用enalbe-eip-snat时会影响自定义vpc使用该公网功能
- 删除lrp类型的eip时删除lrp，否则可能出现lrp资源层次的ip冲突
- 自定义vpc可单独使用vpc的公网功能，不依赖默认vpc的enable-eip-snat特性

#### Which issue(s) this PR fixes:
Fixes #2446

### CODE REVIEW

**Comment by zhangzujian** [comment]
CRD should be also updated in the following files:

```txt
yamls/crd.yaml
kubeovn-helm/templates/kube-ovn-crd.yaml
```

File: pkg/ovs/ovn-nbctl-legacy.go [hunk 1]
```diff
@@ -1178,7 +1178,7 @@ func parseLrRouteListOutput(output string) (routeList []*StaticRoute, err error)
 			NextHop: fields[1],
 		}
 		if ecmpSymmetricReply {
-			route.ECMP = "ecmp-symmetric-reply"
+			route.ECMPMode = "ecmp-symmetric-reply"
```
Comment (zhangzujian) [inline pkg/ovs/ovn-nbctl-legacy.go:1181]:
```suggestion
			route.ECMPMode = util.StaicRouteBfdEcmp
```

**Review by oilbeater — APPROVED** [review]
