### PR TITLE
avoid concurrent subnet status update

### LINKED ISSUE #1975: Incorrect IP statistics in subnet status after subnet expansion
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

1. Create a subnet with CIDR 10.21.0.0/30;
2. Create a deployment with 2 replication;
3. A pod within the deployment is running and the other is stuck on NoAvailableAddress;
4. Change the subnet CIDR to 10.21.0.0/29;
5. Both the Pods are running;
6. There is a chance that the IP statistics in the subnet status are incorrect.

```yaml
  v4availableIPs: 4  # should be 3
  v4usingIPs: 1      # should be 2
  v6availableIPs: 0
  v6usingIPs: 0
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

### PR DESCRIPTION
**Pull request by zhangzujian**
- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

#### What type of this PR

- Bug fixes

#### Which issue(s) this PR fixes:
Fixes #1975

### CODE REVIEW

File: pkg/controller/subnet.go [hunk 1]
```diff
@@ -1390,6 +1393,13 @@ func calcDualSubnetStatusIP(subnet *kubeovnv1.Subnet, c *Controller) error {
 		v6availableIPs = 0
 	}
 
+	if subnet.Status.V4AvailableIPs == v4availableIPs &&
+		subnet.Status.V6AvailableIPs == v6availableIPs &&
+		subnet.Status.V4UsingIPs == usingIPs &&
```
Comment (hongzhen-ma) [inline pkg/controller/subnet.go:1398]: 支持双栈之后，usingIPs  应该是区分成了 v4UsingIPs 和 v6UsingIPs 两个值

**Review by hongzhen-ma — CHANGES_REQUESTED** [review]

File: pkg/controller/subnet.go (hunk 1 above)
Comment (zhangzujian) [reply pkg/controller/subnet.go:1398]: 原代码有问题？我只看到 usingIPs，并没有作区分。

Comment (hongzhen-ma) [reply pkg/controller/subnet.go:1398]: 我看错代码分支了
