### PR TITLE
No need to change deivceID to sriov_netdevice.

### LINKED ISSUE #1903: When delete pod with sriov nic, vf not return to the original condition.
# Expected Behavior
when pod is deleted, set vf mac 00:00:00:00:00:00

# Actual Behavior
do nothing

# Steps to Reproduce the Problem

1. create a pod with mellanox cx-6 vf
2. delete this pod

# Q
What is the effect?
https://github.com/kubeovn/kube-ovn/blob/dbe4ebb31496d959768dd6d451939b11f831856a/pkg/daemon/handler.go#L426-L431

After change deviceID from `00:af:0x.x` to `mellanox.com/cx5_sriov_switchdev:`
will do nothing when delete pod with sriov nic
https://github.com/kubeovn/kube-ovn/blob/dbe4ebb31496d959768dd6d451939b11f831856a/pkg/daemon/ovs_linux.go#L152-L174

Should we delete this part code, when I use kata with kube-ovn sriov, always get old mac if don't set mac to 00:00:00:00:00:00

### PR DESCRIPTION
**Pull request by xujunjie-cover**
- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

#### What type of this PR
Examples of user facing changes:

- Bug fixes

#### Which issue(s) this PR fixes:
Fixes #1903

### CODE REVIEW

File: pkg/daemon/ovs_linux.go [hunk 1]
```diff
@@ -153,13 +153,19 @@ func (csh cniServerHandler) deleteNic(podName, podNamespace, containerID, netns,
 		hostLink, err := netlink.LinkByName(nicName)
 		if err != nil {
 			// If link already not exists, return quietly
+			// E.g. Remove ovs port had delete internal port
```
Comment (oilbeater) [inline pkg/daemon/ovs_linux.go:156]: had -> and

**Review by oilbeater — CHANGES_REQUESTED** [review]

File: pkg/daemon/ovs_linux.go (hunk 1 above)
Comment (xujunjie-cover) [reply pkg/daemon/ovs_linux.go:156]: 这里意思是当操作 internal port 的情况，上面 Remove ovs port 就已经删掉了 internal port，所以会出现已经不存在的情况。英文写的不好，我改一下。

**Review by oilbeater — APPROVED** [review]

**Comment by oilbeater** [comment]
Thanks! @xujunjie-cover
