### PR TITLE
fix: ovs gc just for pod if

### LINKED ISSUE #2085: ovs port gc reports error when the host nic used in underlay is missing
# Expected Behavior

# Actual Behavior

```txt
I1126 06:29:46.110753   13460 ovs-vsctl.go:197] error interfaces:
 [eth2
"could not open network device eth2 (No such device)]
I1126 06:29:46.120450   13460 ovs-vsctl.go:208] delete lost port eth2
W1126 06:29:46.131957   13460 ovs-vsctl.go:38] ovs-vsctl command error: ovs-vsctl --timeout=30 --if-exists --with-iface del-port br-int eth2 in 11ms
E1126 06:29:46.132102   13460 ovs-vsctl.go:211] failed to delete ovs port failed to run 'ovs-vsctl --timeout=30 --if-exists --with-iface del-port br-int eth2': exit status 1
  "ovs-vsctl: bridge br-int does not have a port eth2\n",
E1126 06:29:59.530802   13460 init.go:172] failed to remove port eth2 from external bridge br-pn-5034: failed to get nic by name eth2: Link not found
E1126 06:29:59.530873   13460 controller.go:220] error syncing 'pn-5034': failed to remove port eth2 from external bridge br-pn-5034: failed to get nic by name eth2: Link not found, requeuing
```

# Steps to Reproduce the Problem

1. Create a provider network using nic eth2 which is a veth interface;
2. Delete eth2;

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

### PR DESCRIPTION
**Pull request by lut777**
- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

#### What type of this PR
Examples of user facing changes:
- Bug fixes

#### Which issue(s) this PR fixes:
Fixes #2085 

1. Now only interfaces of pods(with external netns) will be listed as error ones.
2. bridge name of interface now is identified by interface=>ports=>bridges, but but always br-int.  

delete eth1 and nothing happens:
image

delete pod interface and gc:
image

image

### CODE REVIEW

File: pkg/ovs/ovs-vsctl.go [hunk 1]
```diff
@@ -206,7 +206,23 @@ func CleanLostInterface() {
...
+			if err != nil {
+				klog.Errorf("failed to find related port %v uuid %v", ifUUID[0], err)
+				return
+			}
+			briName, err := ovsFind("bridge", "name", fmt.Sprintf("ports{>=}%s", portUUID[0]))
+			if err != nil {
+				klog.Errorf("failed to find related bridge %v uuid %v", portUUID[0], err)
+				return
+			}
+			output, err := Exec("--if-exists", "--with-iface", "del-port", briName[0], name)
```
Comment (zhangzujian) [inline pkg/ovs/ovs-vsctl.go:225]: We can use `ovs-vsctl del-port <PORT>`, so there is no need to get the bridge name.

**Review by zhangzujian — APPROVED** [review]

File: pkg/ovs/ovs-vsctl.go (hunk 1 above)
Comment (lut777) [reply pkg/ovs/ovs-vsctl.go]: fixed
