### PR TITLE
fix vlan subnet use logical gw can not access outside cluster node

### LINKED ISSUE #2910: external network route via ovn0 cause br-external with ip can not access
# Expected Behavior
should has direct route for br-external
# Actual Behavior
has no direct route for br-external
# Steps to Reproduce the Problem

1. create a cluster with kube-ovn master
1. enable ovn-eip-snat
1. create cust vpc and pn vlan subnet

# Additional Info

- kube-ovn version:
  
  ```
master
  ```

my cluster

``` bash


[root@rocky kube-ovn]# git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
[root@rocky kube-ovn]# diff dist/images/install.sh /root/install.sh
15c15
< ENABLE_NP=${ENABLE_NP:-true}
---
> ENABLE_NP=${ENABLE_NP:-false}
[root@rocky kube-ovn]#

# my cluster only disable NP


# enable ovn-eip-snat

[root@rocky 00-cust-vpc]# cat 00-gw-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ovn-external-gw-config
  namespace: kube-system
data:
  enable-external-gw: "true"
  external-gw-nodes: "rocky"
  type: "distributed"
  external-gw-nic: "eth1" # 用于接入 ovs 公网网桥的网卡




# create custom vpc subnet
[root@rocky 00-cust-vpc]# cat 00-ns.yml
apiVersion: v1
kind: Namespace
metadata:
  name: vpc1

[root@rocky 00-cust-vpc]# cat 01-vpc-enable-external.yaml
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: vpc1
spec:
  namespaces:
  - vpc1
  enableExternal: true
[root@rocky 00-cust-vpc]# cat 02-subnet.yml
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: vpc1-subnet1
spec:
  cidrBlock: 192.168.10.0/24
  default: false
  disableGatewayCheck: false
  disableInterConnection: true
  enableEcmp: false
  gatewayNode: ""
  gatewayType: distributed
  natOutgoing: false
  private: false
  protocol: IPv4
  provider: ovn
  vpc: vpc1
  namespaces:
  - vpc1
  

# create pn vlan subnet

[root@rocky 00-provider-net-work]# cat 01-provider-network.yaml
apiVersion: kubeovn.io/v1
kind: ProviderNetwork
metadata:
  name: external
spec:
  defaultInterface: eth1
[root@rocky 00-provider-net-work]# cat 02-vlan.yaml
apiVersion: kubeovn.io/v1
kind: Vlan
metadata:
  name: vlan0
spec:
  id: 0
  provider: external
[root@rocky 00-provider-net-work]# cat 03-vlan-subnet.yaml
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: external
spec:
  protocol: IPv4
  cidrBlock: 10.10.10.0/24
  logicalGateway: true
  vlan: vlan0
  excludeIps:
  - 172.20.0.1..172.20.0.20
 

```

and you will see the external network has no direct route, it looks like replaced by `via ovn0`, which will cause i can not access my server via br-external ip

```

57: br-external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 4c:e1:73:47:0b:d6 brd ff:ff:ff:ff:ff:ff
    inet 10.10.10.20/24 scope global br-external
       valid_lft forever preferred_lft forever
    inet6 fe80::4ee1:73ff:fe47:bd6/64 scope link
       valid_lft forever preferred_lft forever


[root@rocky 00-provider-net-work]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.20.10.1     0.0.0.0         UG    600    0        0 wlp0s20f3
10.10.10.0      100.64.0.1      255.255.255.0   UG    0      0        0 ovn0 # can not access by br-external ip
10.16.0.0       100.64.0.1      255.255.0.0     UG    0      0        0 ovn0
100.64.0.0      0.0.0.0         255.255.0.0     U     0      0        0 ovn0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-2cd96eccde7a
172.19.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-c3ef217d7024
172.20.10.0     0.0.0.0         255.255.255.240 U     600    0        0 wlp0s20f3

# it has no direct route for br-external

```

### PR DESCRIPTION
**Pull request by bobz965**
- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

### What type of this PR
Examples of user facing changes:
- Bug fixes

### Which issue(s) this PR fixes:
Fixes #2910 

### <samp>🤖 Generated by Copilot at 2084e75</samp>

Simplify the condition for skipping subnets in `reconcileRouters` by removing a redundant check. Refactor the function to use a single loop for better performance and readability.

### <samp>🤖 Generated by Copilot at 2084e75</samp>

> _`reconcileRouters`_
> _Simpler condition, one loop_
> _Autumn leaves fall fast_

### <samp>🤖 Generated by Copilot at 2084e75</samp>

*  Simplify the condition for skipping a subnet in `reconcileRouters` by removing the redundant `subnet.Spec.LogicalGateway` check ([link](https://github.com/kubeovn/kube-ovn/pull/3007/files?diff=unified&w=0#diff-2fc809b47dbb2a514497bf5e38d53de7bafc66f8dc976c817d1e5dac9d723c20L199-R199))

### CODE REVIEW

File: pkg/daemon/controller_linux.go [hunk 1]
```diff
@@ -284,6 +287,17 @@ func routeDiff(existRoutes []netlink.Route, cidrs, joinCIDR []string, gateway st
...
+		for _, ar := range allRoutes {
+			if ar.Dst.String() == route.Dst.String() && ar.LinkIndex != route.LinkIndex {
+				// route conflict
+				conflict = true
+				break
+			}
+		}
+		if conflict {
+			toDel = append(toDel, route)
+		}
```
Comment (zhangzujian) [inline pkg/daemon/controller_linux.go:300]: Is it necessary to check conflict?

File: pkg/daemon/controller_linux.go [hunk 2]
```diff
@@ -305,7 +319,17 @@ func routeDiff(existRoutes []netlink.Route, cidrs, joinCIDR []string, gateway st
 		}
 
 		found := false
-		for _, r := range existRoutes {
+		for _, ar := range allRoutes {
+			if ar.Dst.String() == c {
```
Comment (zhangzujian) [inline pkg/daemon/controller_linux.go:323]:
```suggestion
			if ar.Dst != nil && ar.Dst.String() == c {
```

File: pkg/daemon/controller_linux.go (hunk 1 above)
Comment (bobz965) [reply pkg/daemon/controller_linux.go:300]: sometimes, after node restart, the ip transfer to br-external is after this logic, so a route to ovn0 has add
and after br-external own its ip, the conflict route should be detected and clean.

File: pkg/daemon/controller_linux.go [hunk 3]
```diff
@@ -196,7 +196,7 @@ func (c *Controller) reconcileRouters(event *subnetEvent) error {
 	joinCIDR := make([]string, 0, 2)
 	cidrs := make([]string, 0, len(subnets)*2)
 	for _, subnet := range subnets {
-		if (subnet.Spec.Vlan != "" && !subnet.Spec.LogicalGateway) || subnet.Spec.Vpc != c.config.ClusterRouter || !subnet.Status.IsReady() {
+		if subnet.Spec.Vpc != c.config.ClusterRouter || !subnet.Status.IsReady() {
```
Comment (zhangzujian) [inline pkg/daemon/controller_linux.go:199]: Why is `subnet.Spec.Vlan != "" && !subnet.Spec.LogicalGateway` deleted?

Comment (bobz965) [reply pkg/daemon/controller_linux.go:199]: I will recover this， this could filter cidr before later diff routes

File: pkg/daemon/controller_linux.go [hunk 4]
```diff
@@ -284,6 +287,17 @@ func routeDiff(existRoutes []netlink.Route, cidrs, joinCIDR []string, gateway st
 		if !found {
 			toDel = append(toDel, route)
 		}
+		conflict := false
+		for _, ar := range allRoutes {
+			if ar.Dst.String() == route.Dst.String() && ar.LinkIndex != route.LinkIndex {
```
Comment (zhangzujian) [inline pkg/daemon/controller_linux.go:292]: Check if `ar.Dst` is `nil`.

File: pkg/daemon/controller_linux.go (hunk 2 above)
Comment (zhangzujian) [inline pkg/daemon/controller_linux.go:323]: Check if `ar.Dst` is `nil`.

Comment (bobz965) [reply pkg/daemon/controller_linux.go]: fixed

**Review by zhangzujian — APPROVED** [review]
