### PR TITLE
SgPorts should be updated when pod deleted

### LINKED ISSUE #3515: address_set doesn't update when pod with security group has been deleted
# Bug Report

## Steps to Reproduce the Problem

1、创建安全组sg1
2、创建Pod绑定安全组sg1
3、删除Pod前后查看address_set

## Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```bash
  (paste your output here)

  ```

- kube-ovn version:
  
  ```bash
  (paste your output here)

  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**

  ```bash
  (paste your output here)
  
  ```

### PR DESCRIPTION
**Pull request by zcq98**
# Pull Request

- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR

Examples of user facing changes:

- Bug fixes

## Which issue(s) this PR fixes

Fixes #3515 

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at af0a342</samp>

Fix security group port synchronization when deleting pods with port security. Add code to `pkg/controller/pod.go` to enqueue security group names for processing when a pod with port security is deleted.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at af0a342</samp>

> _`handleDeletePod`_
> _Syncs security groups now_
> _A bug fix for fall_

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at af0a342</samp>

*  Trigger security group port sync when deleting pod with port security ([link](https://github.com/kubeovn/kube-ovn/pull/3516/files?diff=unified&w=0#diff-449e8d1bd46b9c978e208dde912a1d7a76d17ce553067f8d0a67a27f17338d26R1110-R1119))

### CODE REVIEW

File: pkg/controller/pod.go [hunk 1]
```diff
@@ -1107,6 +1107,16 @@ func (c *Controller) handleDeletePod(key string) error {
 	}
 	for _, podNet := range podNets {
 		c.syncVirtualPortsQueue.Add(podNet.Subnet.Name)
+		if pod.Annotations[fmt.Sprintf(util.PortSecurityAnnotationTemplate, podNet.ProviderName)] == "true" {
+			securityGroupAnnotation := pod.Annotations[fmt.Sprintf(util.SecurityGroupAnnotationTemplate, podNet.ProviderName)]
```
Comment (bobz965) [inline pkg/controller/pod.go:1111]: securityGroupAnnotation 先判断下是否为空，提前跳过

**Review by bobz965 — APPROVED** [review]
