### PR TITLE
[performance] in large-scale clusters, init node router policy too slow

### LINKED ISSUE #4849: [BUG] When kube-ovn-controller restarts, need takes a long time to start process queue tasks
### Kube-OVN Version

v1.12.29

### Kubernetes Version

v1.28.11

### Operation-system/Kernel Version

"CentOS Linux 7 (Core)"   5.10.0-228.2410.el7.bzl.x86_64

### Description

1. when kube-ovn-controller restarts, need takes a long time(1 hour+) to start process queue tasks in a large cluster(2000+Node,15w+Pod,100+subnet)
2. work queue depth monitor
image

### Steps To Reproduce

1. creating a large cluster(2000+Node,15w+Pod,100+subnet)
2. restart kube-ovn-controller pod

### Current Behavior

need takes a long time(1 hour+) to start queue tasks process

### Expected Behavior

fast to start queue tasks process

### PR DESCRIPTION
**Pull request by cmdy**
# Pull Request

- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR

Examples of user facing changes:

- Features
- Bug fixes
- Docs
- Tests

## Which issue(s) this PR fixes

Fixes #4849

PR #4884 merge into master branch

### CODE REVIEW

**Comment by cmdy** [comment]
@oilbeater  PTAL

File: pkg/controller/vpc.go [hunk 1]
```diff
@@ -761,6 +762,38 @@ func (c *Controller) addPolicyRouteToVpc(vpcName string, policy *kubeovnv1.Polic
...
+func buildExternalIDsMapKey(match, action string, priority int) string {
+	return fmt.Sprintf("%s-%s-%d", match, action, priority)
+}
+
+func (c *Controller) batchAddPolicyRouteToVpc(name string, policies []*kubeovnv1.PolicyRoute, externalIDs map[string]map[string]string) error {
+	if len(policies) == 0 {
+		return nil
+	}
+	start := time.Now()
+	lrps := make([]*ovnnb.LogicalRouterPolicy, 0, len(policies))
```
Comment (zhangzujian) [inline pkg/controller/vpc.go:774]: `LRP` means Logical Router Port, we need to change this variable name.

**Comment by zhangzujian** [comment]
VPC Eregss Gateway e2e test failed. Seems like the LR policy created by egress gateway is deleted. Is there any chance that the LR policy is deleted by the change in this PR?

File: pkg/controller/vpc.go (hunk 1 above)
Comment (cmdy) [reply pkg/controller/vpc.go:774]: ok，we use  an clear meaning variable name

**Comment by cmdy** [comment]
> VPC Eregss Gateway e2e test failed. Seems like the LR policy created by egress gateway is deleted. Is there any chance that the LR policy is deleted by the change in this PR?

this PR does not delete the LR policy by egress gateway

File: pkg/ovs/ovn.go [hunk 2]
```diff
@@ -63,6 +64,14 @@ func NewOvnNbClient(ovnNbAddr string, ovnNbTimeout, ovsDbConTimeout, ovsDbInacti
 		return nil, err
 	}
 
+	dbModel.SetIndexes(map[string][]model.ClientIndex{
```
Comment (oilbeater) [inline pkg/ovs/ovn.go:67]: priority 大部分是一样的是不是不用建索引了，或者比较一下效果

Comment (cmdy) [reply pkg/ovs/ovn.go:67]: 这里主要用了priority 和 match 做联合索引，但是考虑到如果其中某一个刚好没有值的话，就会变成索引；libovsdb 这个客户端索引，如果不明确指定索引字段的话就会完全查不出来结果；所以这里就除了联合索引外还额外为priority和match 做了单索引配置；另 这里我这边主要对比了where 和 whercache方法的查询效率，在建立索引情况下，表数据量级较大(20w)情况下,单次同条件查询Where 要比WherCache 大概快100~200ms左右，如果需要的话我整理一下具体对比数据

**Comment by oilbeater** [comment]
@cmdy Thanks for this great work!
