### PR TITLE
fix(vm/sts): handle multiple network interfaces when cleaning resourc…

### LINKED ISSUE #5933: [BUG] VM 多网卡场景下，VM POD删除时资源清理未考虑多网卡的情况
### Kube-OVN Version

v1.15.0

### Kubernetes Version

v1.29.5

### Operation-system/Kernel Version

"Ubuntu 24.04.3 LTS" 6.8.0-79-generic

### Description

Image

### Steps To Reproduce

1、VM配置多网卡（只指定子网，不指定IP地址）
2、VM开机
3、此时修改VM上第一张网卡子网的annotation（将子网修改成另一个子网）
4、此时关机重启，可以发现**第一张网卡子网切换成功的同时，第二张网卡的IP地址也重新分配了**

### Current Behavior

多网卡场景下第一张默认网卡的子网修改会引发第二张网卡的IP变化

### Expected Behavior

多网卡场景下第一张默认网卡的子网修改不会引入对其它网卡的影响

### PR DESCRIPTION
**Pull request by zhaocongqi**
fix(vm/sts): handle multiple network interfaces when cleaning resources on VM Pod deletion

# Pull Request

- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR

Examples of user facing changes:

- Bug fixes

## Which issue(s) this PR fixes

Fixes #5933

### CODE REVIEW

File: pkg/controller/pod.go [hunk 1]
```diff
@@ -2212,102 +2220,132 @@ func (c *Controller) acquireStaticAddress(key, nicName, ip string, mac *string,
...
+			ownerRefAnnotations = vm.Spec.Template.ObjectMeta.Annotations
+		}
+	}
+
+	var ipcrToDelete []string
+	if defaultIPCRName := appendCheckPodNonMultusNetToDel(c, pod, ownerRefName, ownerRefAnnotations, podNs); defaultIPCRName != "" {
+		ipcrToDelete = append(ipcrToDelete, defaultIPCRName)
+	}
+
+	if multusIPCRName := appendCheckPodMultusNetToDel(c, pod, ownerRefName, ownerRefAnnotations); len(multusIPCRName) != 0 {
```
Comment (zbb88888) [inline pkg/controller/pod.go]:
```suggestion
	if multusIPCRNames := appendCheckPodMultusNetToDel(c, pod, ownerRefName, ownerRefAnnotations); len(multusIPCRName) != 0 {
```

File: pkg/controller/pod.go [hunk 2]
```diff
@@ -2212,102 +2220,132 @@ func (c *Controller) acquireStaticAddress(key, nicName, ip string, mac *string,
...
+			}
+		}
+	}
+	return ""
+}
+
+func appendCheckPodMultusNetToDel(c *Controller, pod *v1.Pod, ownerRefName string, ownerRefAnnotations map[string]string) []string {
+	var multusIPCRName []string
+	attachmentNets, _ := c.getPodAttachmentNet(pod)
+	for _, attachmentNet := range attachmentNets {
```
Comment (zbb88888) [inline pkg/controller/pod.go]:
```suggestion
	for attachmentNet := range attachmentNets {
```

**Comment by zhaocongqi** [comment]
@oilbeater hi, could you help review this？
