### PR TITLE
fix: kube-ovn-controller cannot be ready when ENABLE_METRICS is false

### LINKED ISSUE #4862: [BUG] kube-ovn-controller cannot be ready when ENABLE_METRICS is false
### Kube-OVN Version

v1.14.0

### Kubernetes Version

v1.29.5

### Operation-system/Kernel Version

"Ubuntu 22.04.5 LTS" 6.8.0-50-generic

### Description

1、当关闭metrics high kube-ovn-controller的pod不能ready
2、kube-ovn-controller通过10660端口进行健康检查
image
3、但是当ENABLE_METRICS 设置成false时，conteoller不会开启10660端口的监听
image
4、但是在cni的逻辑中，即使ENABLE_METRICS 设置成false，也会开启10665的监听
image

### Steps To Reproduce

1、helm chart设置ENABLE_METRICS 为false
2、启动kubeovn，发现controller无法启动

### Current Behavior

controller健康检查失败

### Expected Behavior

controller健康检查在关闭metric的情况下能够通过

### PR DESCRIPTION
**Pull request by zhaocongqi**
# Pull Request

- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR

Examples of user facing changes:

- Bug fixes

## Which issue(s) this PR fixes

Fixes #4862

### CODE REVIEW

File: cmd/ovn_monitor/ovn_monitor.go [hunk 1]
```diff
@@ -33,21 +37,46 @@ func CmdMain() {
 	addr := config.ListenAddress
 	if os.Getenv("ENABLE_BIND_LOCAL_IP") == "true" {
 		if ips := strings.Split(os.Getenv("POD_IPS"), ","); len(ips) == 1 {
-			addr = util.JoinHostPort(ips[0], port)
+			addr = ips[0]
```
Comment (bobz965) [inline cmd/ovn_monitor/ovn_monitor.go:40]:
```suggestion
		ip = ips[0] # addr 的意思和上述编码不一致？ 直接用 ip？
```

File: cmd/pinger/pinger.go [hunk 2]
```diff
@@ -30,16 +30,16 @@ func CmdMain() {
 	ctrl.SetLogger(klog.NewKlogr())
 	ctx := signals.SetupSignalHandler()
 	if config.Mode == "server" {
-		if config.EnableMetrics {
-			go func() {
+		go func() {
```
Comment (bobz965) [inline cmd/pinger/pinger.go:33]: 我感觉之前的写法更优

File: cmd/controller/controller.go [hunk 3]
```diff
@@ -84,15 +84,36 @@ func CmdMain() {
...
+				util.LogFatalAndExit(err, "failed to run metrics server")
+			}
+		} else {
+			klog.Info("metrics server is disabled")
+			listerner, err := net.ListenTCP("tcp", &net.TCPAddr{IP: net.ParseIP(metricsAddr), Port: int(config.PprofPort)})
+			if err != nil {
+				util.LogFatalAndExit(err, "failed to listen on %s", util.JoinHostPort(metricsAddr, config.PprofPort))
+			}
+			svr := manager.Server{
+				Name: "metrics",
```
Comment (zhangzujian) [inline cmd/controller/controller.go:101]:
```suggestion
				Name: "health-check",
```

File: cmd/daemon/cniserver.go [hunk 4]
```diff
@@ -149,10 +146,36 @@ func main() {
 		}()
 	}
 
-	listenAddr := util.JoinHostPort(addr, config.PprofPort)
-	if err = metrics.Run(ctx, nil, listenAddr, config.SecureServing, servePprofInMetricsServer); err != nil {
-		util.LogFatalAndExit(err, "failed to run metrics server")
+	if config.EnableMetrics {
+		daemon.InitMetrics()
+		metrics.InitKlogMetrics()
```
Comment (zhangzujian) [inline cmd/daemon/cniserver.go:151]: 移到这里是为了解决什么问题？

File: cmd/controller/controller.go [hunk 5]
```diff
@@ -84,15 +84,36 @@ func CmdMain() {
...
+				Server: &http.Server{
+					Handler:           http.NewServeMux(),
+					MaxHeaderBytes:    1 << 20,
+					IdleTimeout:       90 * time.Second,
+					ReadHeaderTimeout: 32 * time.Second,
+				},
```
Comment (zhangzujian) [inline cmd/controller/controller.go:107]: We need to serve TLS when `config.SecureServing` is true, or do not use TLS in heclth check when metrics is disabled.

File: cmd/controller/controller.go [hunk 6]
```diff
@@ -84,15 +84,36 @@ func CmdMain() {
...
+				Listener: listerner,
+			}
+			go func() {
+				if err = svr.Start(ctx); err != nil {
+					util.LogFatalAndExit(err, "failed to run metrics server")
```
Comment (zhangzujian) [inline cmd/controller/controller.go:112]:
```suggestion
					util.LogFatalAndExit(err, "failed to run health check server")
```

File: pkg/ovnmonitor/config.go [hunk 7]
```diff
@@ -46,17 +44,17 @@ type Configuration struct {
...
 // ParseFlags get parameters information.
 func ParseFlags() (*Configuration, error) {
 	var (
-		argListenAddress = pflag.String("listen-address", ":10661", "Address to listen on for web interface and telemetry.")
-		argMetricsPath   = pflag.String("telemetry-path", "/metrics", "Path under which to expose metrics.")
 		argPollTimeout   = pflag.Int("ovs.timeout", 2, "Timeout on JSON-RPC requests to OVN.")
 		argPollInterval  = pflag.Int("ovs.poll-interval", 30, "The minimum interval (in seconds) between collections from OVN server.")
 		argEnableMetrics = pflag.Bool("enable-metrics", true, "Whether to support metrics query")
 		argSecureServing = pflag.Bool("secure-serving", false, "Whether to serve metrics securely")
+		argPprofPort     = pflag.Int32("pprof-port", 10661, "The port to get profiling data")
```
Comment (zhangzujian) [inline pkg/ovnmonitor/config.go:57]: This port is used for metrics, not profiling.

**Review by zhangzujian — APPROVED** [review]

**Review by bobz965 — APPROVED** [review]
