### PR TITLE
when cidr, gw or exclude_ips change , update subnet ipam

### LINKED ISSUE #2547: when restart deployment ,the released ip sometimes can be used Immediately
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

1.
1.
1.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

https://github.com/kubeovn/kube-ovn/actions/runs/4507562970/jobs/7935511029?pr=2545

### PR DESCRIPTION
**Pull request by changluyi**
- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

### What type of this PR
Examples of user facing changes:
- Features
- Bug fixes
- Docs
- Tests

### Which issue(s) this PR fixes:
Fixes #2547

### <samp>🤖 Generated by Copilot at ca84aa0</samp>

Optimized subnet controller to reduce IPAM updates. Added a flag to `subnet` key to indicate IP changes and checked it in `pkg/controller/subnet.go`.

### <samp>🤖 Generated by Copilot at ca84aa0</samp>

> _Oh we are the subnet controllers, we work with IPAM_
> _We don't like to waste our time on things that don't matter_
> _So we added a flag to the `subnet key`, to check before we update_
> _And we sing as we heave on the count of three, optimize the subnet state_

### <samp>🤖 Generated by Copilot at ca84aa0</samp>

*  Import `strconv` package to enable boolean conversion ([link](https://github.com/kubeovn/kube-ovn/pull/2651/files?diff=unified&w=0#diff-3742843fd11c637b26eae183fb8a0c4eeff96bbfb18a8db1e0ded0c33733f205R9))
*  Modify `enqueueUpdateSubnet` function to append boolean value to subnet key based on CIDR, gateway, or exclude IPs changes ([link](https://github.com/kubeovn/kube-ovn/pull/2651/files?diff=unified&w=0#diff-3742843fd11c637b26eae183fb8a0c4eeff96bbfb18a8db1e0ded0c33733f205R116-R121))
  - Split subnet key into original key and boolean value and parse the latter into `updateIPAM` variable ([link](https://github.com/kubeovn/kube-ovn/pull/2651/files?diff=unified&w=0#diff-3742843fd11c637b26eae183fb8a0c4eeff96bbfb18a8db1e0ded0c33733f205R514-R522))
  - Add condition to check `updateIPAM` before calling IPAM update to skip unnecessary updates ([link](https://github.com/kubeovn/kube-ovn/pull/2651/files?diff=unified&w=0#diff-3742843fd11c637b26eae183fb8a0c4eeff96bbfb18a8db1e0ded0c33733f205L589-R608))

### CODE REVIEW

File: pkg/controller/subnet.go [hunk 1]
```diff
@@ -112,6 +113,12 @@ func (c *Controller) enqueueUpdateSubnet(old, new interface{}) {
 				"gateway node changes from %s to %s ", oldSubnet.Spec.GatewayNode, newSubnet.Spec.GatewayNode)
 		}
 
+		needUpdateIPAM := !reflect.DeepEqual(oldSubnet.Spec.ExcludeIps, newSubnet.Spec.ExcludeIps) ||
+			oldSubnet.Spec.CIDRBlock != newSubnet.Spec.CIDRBlock ||
+			oldSubnet.Spec.Gateway != newSubnet.Spec.Gateway
+
+		key = strings.Join([]string{key, strconv.FormatBool(needUpdateIPAM)}, "#")
```
Comment (oilbeater) [inline pkg/controller/subnet.go:120]: We should not add more complex logical in the enqueue function. Can we check if we should update the ipam in `ipam.AddOrUpdateSubnet`

**Review by oilbeater — CHANGES_REQUESTED** [review]

File: pkg/controller/subnet.go (hunk 1 above)
Comment (changluyi) [reply pkg/controller/subnet.go]: fixed

**Review by oilbeater — APPROVED** [review]
