### PR TITLE
fix SNAT on pod startup

### LINKED ISSUE #732: External network past SNAT unavailable on pod start
Following our discussion on Slack, we confirmed that any network request to an external network made during 0-3 seconds after pod start is blocked and as a result lots of pod are failing (such as pod executing helm or curl or git clone as their first CMD).
During investigation we confirmed that this behavior occurs only on requests made to external network, which lead us to look at the SNAT implementation.
It seems that when the CNI is attaching the network, it return success if the pod gateway is pingable, but at that time the SNAT rules for external access are not installed yet, because they are installed and updated every 3 seconds by ipset/iptables. This causes in turn the requests to external network to be blocked and most commands are waiting forever until the pod fails.
This can be reproduced using a pod run command like this one : 
`kubectl run testcurl --image=centos:8 --restart=Never -- sh -c 'for i in $(seq 1 10); do echo $i ; date; curl -vsI --connect-timeout 0.5 https://www.google.com/; echo ; sleep 0.1; done'`

On other implementations, the logs show that the external network is always ready on the first request, where as in kube-ovn this happens only a few (1-3) seconds after pod creation.

### PR DESCRIPTION
**Pull request by zhangzujian**
Fix #732 by updating ipset *local-pod-ip-nat* when adding/deleting nic.

### CODE REVIEW

File: pkg/daemon/gateway.go [hunk 1]
```diff
@@ -106,6 +106,88 @@ func (c *Controller) setIPSet() error {
 	return nil
 }
 
+func (c *Controller) addIPSetMembers(setID, subnet, ip string) {
```
Comment (oilbeater) [inline pkg/daemon/gateway.go:109]: should return err if something goes wrong

File: pkg/daemon/gateway.go [hunk 2]
```diff
@@ -106,6 +106,88 @@ func (c *Controller) setIPSet() error {
...
+
+	protocols := make([]string, 2)
+	if c.protocol == kubeovnv1.ProtocolDual {
+		protocols[0] = kubeovnv1.ProtocolIPv4
+		protocols[1] = kubeovnv1.ProtocolIPv6
+	} else {
+		protocols[0] = c.protocol
+	}
+
+	podIPs := strings.Split(ip, ",")
```
Comment (oilbeater) [inline pkg/daemon/gateway.go:130]: Check ip protocol directly and add it to related ipset, no need to create `protocols` array

File: pkg/daemon/gateway.go [hunk 3]
```diff
@@ -106,6 +106,88 @@ func (c *Controller) setIPSet() error {
...
```
Comment (oilbeater) [inline pkg/daemon/gateway.go:171]: same as above

File: pkg/daemon/handler.go [hunk 4]
```diff
@@ -116,6 +116,8 @@ func (csh cniServerHandler) handleAdd(req *restful.Request, resp *restful.Respon
 			}
 			return
 		}
+
+		csh.Controller.addIPSetMembers(LocalPodSet, subnet, ip)
```
Comment (oilbeater) [inline pkg/daemon/handler.go:120]: should check error here

File: pkg/daemon/handler.go [hunk 5]
```diff
@@ -208,6 +210,10 @@ func (csh cniServerHandler) handleDel(req *restful.Request, resp *restful.Respon
 
 	klog.Infof("delete port request %v", podRequest)
 	if podRequest.Provider == util.OvnProvider || podRequest.CniType == util.CniTypeName {
+		subnet := pod.Annotations[fmt.Sprintf(util.LogicalSwitchAnnotationTemplate, podRequest.Provider)]
+		ip := pod.Annotations[fmt.Sprintf(util.IpAddressAnnotationTemplate, podRequest.Provider)]
+		csh.Controller.removeIPSetMembers(LocalPodSet, subnet, ip)
```
Comment (oilbeater) [inline pkg/daemon/handler.go:215]: check error here

**Review by oilbeater — CHANGES_REQUESTED** [review]

File: pkg/daemon/gateway.go [hunk 6]
```diff
@@ -106,6 +106,68 @@ func (c *Controller) setIPSet() error {
...
+		return err
+	}
+
+	if !podSubnet.Spec.NatOutgoing ||
+		podSubnet.Spec.Vpc != util.DefaultVpc ||
+		podSubnet.Spec.GatewayType != kubeovnv1.GWDistributedType {
+		return nil
+	}
+
+	protocols := make([]string, 2)
```
Comment (oilbeater) [inline pkg/daemon/gateway.go:122]: no need here

**Review by oilbeater — CHANGES_REQUESTED** [review]

**Comment by oilbeater** [comment]
please squash to one commit

**Review by oilbeater — APPROVED** [review]
